import type { Platform, StackManifest, StackOperations, SupportLevel } from "./types";

const operations = (level: SupportLevel, preview = true): StackOperations => ({ create: level === 4, inspect: level >= 1, edit: level >= 2, install: level >= 3, run: level >= 3, build: level >= 3, test: level >= 3, lint: level >= 3, debug: level >= 3, preview: level >= 3 && preview, package: level === 4, export: level >= 2, deploy: false });
const manifest = (stackId: string, displayName: string, platforms: Platform[], level: SupportLevel, traits: string[], bestFor: string[], required: string[], commands: Partial<StackManifest["commands"]>, limitations: string[] = [], databases: string[] = []): StackManifest => ({
  stackId, version: 1, displayName, status: level === 4 ? "certified" : level === 3 ? "buildable" : level === 2 ? "editable" : "recognized", supportLevel: level,
  supportedPlatforms: platforms, bestFor, avoidFor: [], requiredCapabilities: [], supportedProjectFamilies: [], toolchain: { required, optional: [] }, operations: operations(level, !platforms.includes("api")),
  commands: { install: [], development: [], build: [], test: [], lint: [], package: [], ...commands }, artifacts: platforms.includes("web") ? ["browser-preview"] : platforms.includes("api") ? ["api-playground"] : platforms.includes("android") ? ["android-artifact"] : platforms.includes("windows") ? ["windows-desktop-artifact"] : platforms.includes("game") ? ["game-artifact"] : ["cli-surface"],
  supportedDatabases: databases, supportedAuth: [], supportedDeploymentTargets: [], knownLimitations: limitations, traits,
  certification: { testSuiteVersion: level === 4 ? "1" : "", lastPassedAt: level === 4 ? "repository-baseline" : "", environment: ["foundry-runtime"], passRate: level === 4 ? 1 : 0 },
});

export const STACK_MANIFESTS: StackManifest[] = [
  manifest("static-web-vite", "Static HTML + CSS + JavaScript", ["web"], 4, ["content-first","simple","no-server"], ["landing pages","portfolios","small catalogues","static informational websites","simple browser utilities"], [], { install:[], development:[], build:[], test:[], lint:[], package:[] }),
  manifest("react-vite-typescript", "React + Vite + TypeScript", ["web"], 4, ["frontend-heavy","interactive","separate-api"], ["dashboards","internal tools","single-page apps"], ["node","npm"], { install:["npm install"], development:["npm run dev"], build:["npm run build"], test:["npm test"], lint:["npm run lint"], package:["npm run build"] }),
  manifest("nextjs-typescript-postgres", "Next.js + TypeScript + PostgreSQL", ["web","api"], 4, ["full-stack","relational","multi-user","auth","payments","reporting"], ["saas","portals","inventory","commerce","booking"], ["node","npm"], { install:["npm install"], development:["npm run dev"], build:["npm run build"], test:["npm test"], lint:["npm run lint"], package:["npm run build"] }, [], ["PostgreSQL","SQLite","Supabase"]),
  manifest("node-typescript-api", "Node.js + TypeScript API", ["api","cli"], 4, ["service-only","realtime","webhooks","integrations"], ["apis","webhook services","business services"], ["node","npm"], { install:["npm install"], development:["npm run dev"], build:["npm run build"], test:["npm test"], lint:["npm run lint"], package:["npm pack"] }, [], ["PostgreSQL","MySQL","SQLite","MongoDB"]),
  manifest("python-fastapi", "Python + FastAPI", ["api"], 4, ["data-heavy","ai","automation","document-processing"], ["ai services","data processing","automation"], ["python"], { install:["python -m pip install -r requirements.txt"], development:["python -m uvicorn app.main:app --reload"], build:["python -m build"], test:["python -m pytest"], lint:["python -m ruff check ."], package:["python -m build"] }, [], ["PostgreSQL","SQLite"]),
  manifest("dotnet-web-api", ".NET Web API", ["api"], 4, ["enterprise","microsoft","strongly-typed"], ["enterprise services","Microsoft environments"], ["dotnet"], { development:["dotnet run"], build:["dotnet build"], test:["dotnet test"], package:["dotnet publish"] }, [], ["SQL Server","PostgreSQL"]),
  manifest("android-kotlin-compose", "Kotlin + Jetpack Compose + Room", ["android"], 4, ["native-android","hardware","offline","barcode","bluetooth","nfc"], ["scanner apps","rugged devices","Android-only apps"], ["java","android"], { install:["foundry android ensure-sdk"], development:["foundry android launch"], build:["gradlew assembleDebug"], test:["gradlew testDebugUnitTest"], lint:["gradlew lintDebug"], package:["gradlew bundleRelease"] }, ["Physical hardware workflows require the named device and safe test credentials; Foundry reports them separately from build completion."], ["SQLite"]),
  manifest("ios-swiftui", "Swift + SwiftUI", ["ios"], 4, ["native-ios","apple","hardware"], ["Apple-first applications"], ["xcode","swift"], { development:["xcrun simctl launch"], build:["xcodebuild build"], test:["xcodebuild test"], package:["xcodebuild archive"] }, ["Final build, simulator/device testing, signing, archive, and export run on a connected Mac or Foundry macOS builder."]),
  manifest("flutter-mobile", "Flutter + Dart", ["android","ios"], 4, ["cross-platform","offline","shared-ui"], ["consumer and business mobile apps"], ["flutter","android"], { install:["flutter pub get"], development:["flutter run"], build:["flutter build apk"], test:["flutter test"], lint:["flutter analyze"], package:["flutter build appbundle"] }, ["iOS packaging runs through a connected Mac or Foundry macOS builder."], ["SQLite","Firebase"]),
  manifest("wpf-dotnet", ".NET WPF + SQLite", ["windows"], 4, ["windows-native","hardware","offline","enterprise"], ["Windows business and hardware-control software"], ["dotnet"], { development:["dotnet run"], build:["dotnet build"], test:["dotnet test"], package:["dotnet publish"] }, ["Hardware behavior requires the named device and its licensed SDK when applicable."], ["SQLite","SQL Server"]),
  manifest("electron-typescript", "Electron + React + TypeScript", ["windows","macos","linux"], 4, ["cross-platform","desktop","filesystem"], ["cross-platform desktop applications"], ["node","npm"], { install:["npm install"], development:["npm run dev"], build:["npm run build"], test:["npm test"], lint:["npm run lint"], package:["npm run package"] }, [], ["SQLite"]),
  manifest("tauri-rust", "Tauri + React + TypeScript + Rust", ["windows","macos","linux"], 4, ["cross-platform","desktop","filesystem","lightweight"], ["lightweight cross-platform desktop applications"], ["node","rust"], { install:["npm install"], development:["cargo tauri dev"], build:["cargo tauri build"], test:["cargo test"], lint:["cargo clippy -- -D warnings"], package:["cargo tauri build"] }, [], ["SQLite"]),
  manifest("phaser-typescript", "Phaser + TypeScript + Vite", ["game","web"], 4, ["browser-game","2d","playable-runtime"], ["browser games","interactive experiences"], ["node","npm"], { install:["npm install"], development:["npm run dev"], build:["npm run build"], test:["npm test"], package:["npm run build"] }, []),
  manifest("godot", "Godot", ["game"], 4, ["2d","3d","game-engine"], ["indie games","educational games"], ["godot"], { development:["godot --path ."], build:["godot --headless --editor --path . --quit"], test:["godot --headless --path . --script res://tests/run.gd"], package:["godot --headless --export-release"] }, []),
  manifest("unity", "Unity", ["game"], 4, ["advanced-3d","game-engine"], ["advanced 3D and simulations"], ["unity"], { development:["unity-editor -projectPath ."], build:["unity-editor -batchmode -quit -projectPath . -executeMethod Foundry.Build"], test:["unity-editor -batchmode -runTests -testPlatform EditMode -projectPath ."], package:["unity-editor -batchmode -quit -projectPath . -executeMethod Foundry.Build"] }, ["Unity requires an installed licensed Editor; Foundry preserves and resumes the mission through license setup."]),
];

export function stackManifest(id: string) { return STACK_MANIFESTS.find((item) => item.stackId === id); }
export function manifestForDisplayName(name: string) { const n=name.toLowerCase(); return STACK_MANIFESTS.find((item)=>n.includes(item.displayName.toLowerCase())||item.displayName.toLowerCase().includes(n)); }
