import type { ExecutionReadinessState, Platform, StackManifest } from "./types";

export type RuntimeOperation = "create"|"install"|"run"|"build"|"test"|"lint"|"debug"|"preview"|"package"|"export";
export type RuntimeCommand = { operation:RuntimeOperation; command:string; artifact?:string; localPlatforms?: Platform[]; remotePlatform?:"macos"|"windows"|"linux"; optional?:boolean };
export type CertifiedRuntimeAdapter = {
  stackId:string; scaffoldKind:string; toolchains:string[]; commands:RuntimeCommand[]; artifacts:string[];
  recoveries:Array<{pattern:string; action:string}>; readinessWithoutTools:ExecutionReadinessState;
};

export const CERTIFIED_RUNTIME_ADAPTERS:CertifiedRuntimeAdapter[]=[
  {stackId:"static-web-vite",scaffoldKind:"static-web",toolchains:[],commands:[{operation:"build",command:"foundry static validate"},{operation:"run",command:"foundry-static-preview",artifact:"browser-preview"},{operation:"preview",command:"foundry-static-preview",artifact:"browser-preview"},{operation:"test",command:"foundry-browser-acceptance"},{operation:"package",command:"foundry static package",artifact:"static-site-package"},{operation:"export",command:"foundry-export",artifact:"source-archive"}],artifacts:["browser-preview","static-site-package","source-archive"],recoveries:[{pattern:"broken asset|404","action":"repair local asset references and rerun browser acceptance"}],readinessWithoutTools:"ready_local"},
  {stackId:"react-vite-typescript",scaffoldKind:"node-web",toolchains:["node"],commands:[{operation:"install",command:"npm install"},{operation:"run",command:"npm run dev",artifact:"browser-preview"},{operation:"build",command:"npm run build"},{operation:"test",command:"npm test"},{operation:"lint",command:"npm run lint"},{operation:"package",command:"npm run build",artifact:"web-dist"},{operation:"export",command:"foundry-export",artifact:"source-archive"}],artifacts:["browser-preview","web-dist","source-archive"],recoveries:[{pattern:"missing package","action":"install compiler-evidenced dependency and retry"}],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"nextjs-typescript-postgres",scaffoldKind:"nextjs-fullstack",toolchains:["node"],commands:[{operation:"install",command:"npm install"},{operation:"run",command:"npm run dev",artifact:"browser-preview"},{operation:"build",command:"npm run build"},{operation:"test",command:"npm test"},{operation:"lint",command:"npm run lint"},{operation:"package",command:"npm run build",artifact:"server-build"},{operation:"export",command:"foundry-export",artifact:"source-archive"}],artifacts:["browser-preview","api-playground","server-build","source-archive"],recoveries:[{pattern:"migration|database unavailable","action":"validate migrations against a disposable local database and preserve production data"}],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"node-typescript-api",scaffoldKind:"node-api",toolchains:["node"],commands:[{operation:"install",command:"npm install"},{operation:"run",command:"npm run dev",artifact:"api-playground"},{operation:"build",command:"npm run build"},{operation:"test",command:"npm test"},{operation:"lint",command:"npm run lint"},{operation:"package",command:"npm pack",artifact:"service-package"},{operation:"export",command:"foundry-export"}],artifacts:["api-playground","service-package","source-archive"],recoveries:[],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"python-fastapi",scaffoldKind:"python-fastapi",toolchains:["python"],commands:[{operation:"install",command:"python -m pip install -r requirements.txt"},{operation:"run",command:"python -m uvicorn app.main:app",artifact:"api-playground"},{operation:"test",command:"python -m pytest"},{operation:"lint",command:"python -m ruff check ."},{operation:"build",command:"python -m build"},{operation:"package",command:"python -m build",artifact:"python-package"},{operation:"export",command:"foundry-export"}],artifacts:["api-playground","python-package","source-archive"],recoveries:[{pattern:"module not found","action":"restore locked Python environment and retry"}],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"dotnet-web-api",scaffoldKind:"dotnet-web-api",toolchains:["dotnet"],commands:[{operation:"install",command:"dotnet restore"},{operation:"run",command:"dotnet run",artifact:"api-playground"},{operation:"build",command:"dotnet build --no-restore"},{operation:"test",command:"dotnet test --no-build"},{operation:"package",command:"dotnet publish -c Release",artifact:"service-package"},{operation:"export",command:"foundry-export"}],artifacts:["api-playground","service-package","source-archive"],recoveries:[],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"android-kotlin-compose",scaffoldKind:"android-kotlin-compose",toolchains:["java","android"],commands:[{operation:"install",command:"foundry android ensure-sdk"},{operation:"build",command:"gradlew assembleDebug",artifact:"apk"},{operation:"test",command:"gradlew testDebugUnitTest"},{operation:"lint",command:"gradlew lintDebug"},{operation:"run",command:"foundry android launch",artifact:"android-emulator"},{operation:"debug",command:"foundry android logcat"},{operation:"package",command:"gradlew bundleRelease",artifact:"aab"},{operation:"export",command:"foundry-export"}],artifacts:["apk","aab","android-emulator","runtime-logs","source-archive"],recoveries:[{pattern:"sdk location|license","action":"repair SDK configuration, accept approved licenses, and resume"},{pattern:"device offline","action":"restart ADB, reconnect the device, and resume the workflow"}],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"flutter-mobile",scaffoldKind:"flutter",toolchains:["flutter","android"],commands:[{operation:"install",command:"flutter pub get"},{operation:"lint",command:"flutter analyze"},{operation:"test",command:"flutter test"},{operation:"build",command:"flutter build apk",artifact:"apk",localPlatforms:["windows","linux","macos"]},{operation:"run",command:"flutter run",artifact:"mobile-preview"},{operation:"package",command:"flutter build appbundle",artifact:"aab"},{operation:"package",command:"flutter build ipa",artifact:"ipa",remotePlatform:"macos"},{operation:"export",command:"foundry-export"}],artifacts:["apk","aab","ipa","mobile-preview","source-archive"],recoveries:[{pattern:"flutter doctor","action":"install or repair the exact missing certified component and resume"}],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"ios-swiftui",scaffoldKind:"ios-swiftui",toolchains:["xcode","swift"],commands:[{operation:"test",command:"xcodebuild test",remotePlatform:"macos"},{operation:"build",command:"xcodebuild build",remotePlatform:"macos"},{operation:"run",command:"xcrun simctl launch",artifact:"ios-simulator",remotePlatform:"macos"},{operation:"package",command:"xcodebuild archive",artifact:"xcarchive",remotePlatform:"macos"},{operation:"export",command:"foundry-export",artifact:"source-archive"}],artifacts:["ios-simulator","xcarchive","ipa","source-archive"],recoveries:[{pattern:"signing|provisioning","action":"open guided Apple signing setup without changing identities automatically"}],readinessWithoutTools:"requires_remote_builder"},
  {stackId:"wpf-dotnet",scaffoldKind:"dotnet-wpf",toolchains:["dotnet"],commands:[{operation:"install",command:"dotnet restore"},{operation:"build",command:"dotnet build --no-restore"},{operation:"test",command:"dotnet test --no-build"},{operation:"run",command:"dotnet run",artifact:"desktop-preview",localPlatforms:["windows"]},{operation:"package",command:"dotnet publish -c Release",artifact:"windows-package",localPlatforms:["windows"]},{operation:"export",command:"foundry-export"}],artifacts:["desktop-preview","windows-package","source-archive"],recoveries:[{pattern:"workload not installed","action":"install the certified .NET desktop workload and resume"}],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"electron-typescript",scaffoldKind:"electron-react",toolchains:["node"],commands:[{operation:"install",command:"npm install"},{operation:"run",command:"npm run dev",artifact:"desktop-preview"},{operation:"build",command:"npm run build"},{operation:"test",command:"npm test"},{operation:"lint",command:"npm run lint"},{operation:"package",command:"npm run package",artifact:"desktop-package"},{operation:"export",command:"foundry-export"}],artifacts:["desktop-preview","desktop-package","source-archive"],recoveries:[],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"tauri-rust",scaffoldKind:"tauri-react",toolchains:["node","rust"],commands:[{operation:"install",command:"npm install"},{operation:"build",command:"cargo tauri build",artifact:"desktop-package"},{operation:"test",command:"cargo test"},{operation:"lint",command:"cargo clippy -- -D warnings"},{operation:"run",command:"cargo tauri dev",artifact:"desktop-preview"},{operation:"package",command:"cargo tauri build",artifact:"desktop-package"},{operation:"export",command:"foundry-export"}],artifacts:["desktop-preview","desktop-package","source-archive"],recoveries:[{pattern:"linker|webview","action":"install the certified platform prerequisite and resume"}],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"phaser-typescript",scaffoldKind:"phaser",toolchains:["node"],commands:[{operation:"install",command:"npm install"},{operation:"run",command:"npm run dev",artifact:"playable-preview"},{operation:"build",command:"npm run build"},{operation:"test",command:"npm test"},{operation:"package",command:"npm run build",artifact:"browser-game"},{operation:"export",command:"foundry-export"}],artifacts:["playable-preview","browser-game","source-archive"],recoveries:[],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"godot",scaffoldKind:"godot",toolchains:["godot"],commands:[{operation:"run",command:"godot --path .",artifact:"playable-preview"},{operation:"build",command:"godot --headless --editor --path . --quit"},{operation:"test",command:"godot --headless --path . --script res://tests/run.gd"},{operation:"package",command:"godot --headless --export-release",artifact:"game-package"},{operation:"export",command:"foundry-export"}],artifacts:["playable-preview","game-package","source-archive"],recoveries:[{pattern:"import error","action":"reimport assets with the certified engine version and rerun validation"}],readinessWithoutTools:"installable_by_foundry"},
  {stackId:"unity",scaffoldKind:"unity",toolchains:["unity"],commands:[{operation:"build",command:"unity-editor -batchmode -quit -projectPath . -executeMethod Foundry.Build",artifact:"game-package"},{operation:"test",command:"unity-editor -batchmode -runTests -testPlatform EditMode -projectPath ."},{operation:"run",command:"unity-editor -projectPath .",artifact:"playable-preview"},{operation:"package",command:"unity-editor -batchmode -quit -projectPath . -executeMethod Foundry.Build",artifact:"game-package"},{operation:"export",command:"foundry-export"}],artifacts:["playable-preview","game-package","source-archive"],recoveries:[{pattern:"license","action":"open Unity license setup, preserve the mission, and resume after activation"}],readinessWithoutTools:"requires_user_license"},
];

export function runtimeAdapterFor(stackId:string){return CERTIFIED_RUNTIME_ADAPTERS.find((adapter)=>adapter.stackId===stackId);}
export function assertManifestAdapterCoverage(manifests:StackManifest[]){return manifests.map((manifest)=>({stackId:manifest.stackId,covered:Boolean(runtimeAdapterFor(manifest.stackId))}));}
