import type { TaxonomyEntry } from "./types";

type Seed = Omit<TaxonomyEntry, "subtype" | "keywords"> & { subtypes: string[] };
const seed = (family: string, subtypes: string[], platforms: Seed["platforms"], capabilities: Seed["capabilities"], traits: string[], extra: Partial<Seed> = {}): Seed => ({
  family, subtypes, platforms, capabilities, architecturalTraits: traits, users: ["operators", "administrators"], integrations: [],
  securityRisk: "medium", offline: "possible", hardware: [], scale: "medium", deployments: ["managed-cloud"],
  discoveryQuestions: [], incompatibleAssumptions: [], ...extra,
});

const seeds: Seed[] = [
  seed("websites-content", ["business website","landing page","portfolio","blog","news publication","documentation site","product catalogue","membership site","directory","community site","event website","nonprofit website","school website","professional services website","restaurant website","real estate website","healthcare information website","multilingual website"], ["web"], {}, ["content-first","accessible","responsive"], { securityRisk: "low", offline: "unlikely", scale: "small" }),
  seed("web-applications-saas", ["admin dashboard","customer portal","employee portal","saas product","subscription platform","crm","erp module","inventory management","warehouse management","booking and scheduling","project management","task management","help desk","ticketing","learning management","document management","workflow automation","form builder","survey platform","reporting platform","analytics dashboard","operations dashboard","marketplace","social application","collaboration application","internal business tool"], ["web","api"], { multiUser: true, authentication: true, relationalData: true }, ["full-stack","role-aware","relational"]),
  seed("commerce-payments", ["e-commerce store","marketplace","subscription commerce","order management","pos system","mobile pos","kiosk","invoicing application","billing portal","donation platform","payment dashboard","transaction reporting","merchant portal","gift-card system","payment integration","checkout application","recurring-payment application"], ["web","api"], { multiUser: true, authentication: true, relationalData: true, payments: true, auditHistory: true }, ["payment-sensitive","idempotent","auditable"], { securityRisk: "high" }),
  seed("inventory-logistics", ["retail inventory","warehouse inventory","manufacturing inventory","multi-location inventory","serialized inventory","medical inventory","rental inventory","asset tracking","barcode inventory","receiving application","shipping application","purchase-order system","supplier management","fleet management","dispatch","field-service management","delivery management","route planning","maintenance tracking"], ["web","api"], { multiUser: true, roleBasedAccess: true, relationalData: true, auditHistory: true, reporting: true }, ["transactional","auditable","multi-location"]),
  seed("mobile-applications", ["ios application","android application","cross-platform mobile application","consumer mobile app","business mobile app","field-service app","delivery-driver app","scanner app","offline data-capture app","social app","fitness app","educational app","restaurant app","booking app","financial dashboard app","customer companion app","employee companion app","location-aware app","camera media app","bluetooth-connected app","nfc-connected app","notification-heavy app"], ["android","ios"], { offlineMode: true, notifications: true }, ["touch-first","device-aware"], { hardware: ["camera","bluetooth","nfc"], offline: "likely" }),
  seed("desktop-applications", ["windows business application","macos application","cross-platform desktop app","wpf application","winforms application","electron application","tauri application","hardware-control application","payment-terminal application","data-import utility","batch-processing tool","reporting application","internal administrative tool","kiosk","media tool","file-processing tool","legacy desktop replacement"], ["windows","macos","linux"], { offlineMode: true }, ["installable","local-first"], { deployments: ["installer"] }),
  seed("backend-services", ["rest api","graphql api","webhook service","authentication service","payment service","integration service","background worker","scheduled-job service","data-processing pipeline","file-processing service","notification service","real-time service","microservice","monolith backend","serverless function collection","api gateway","internal service","public developer api"], ["api"], { backgroundJobs: true }, ["service-only","observable"]),
  seed("data-ai", ["data dashboard","data-cleaning tool","import-export system","etl pipeline","reporting engine","search application","semantic search","document analysis","chatbot","ai assistant","ai workflow","image-processing application","recommendation system","classification application","forecasting application","prompt-testing tool","model-evaluation dashboard"], ["api","web"], { fileUploads: true, backgroundJobs: true }, ["data-heavy","asynchronous"]),
  seed("games-interactive", ["2d platformer","3d game","puzzle game","educational game","simulation","strategy game","mobile casual game","browser game","multiplayer game","card game","board-game adaptation","physics game","interactive story","virtual showroom","training simulation","kiosk experience"], ["game"], {}, ["playable-runtime","asset-pipeline"], { securityRisk: "low", deployments: ["game-artifact"] }),
  seed("developer-tools", ["cli tool","sdk","reusable library","package","code generator","testing utility","api client","local developer tool","browser extension","vs code extension","desktop helper","automation script","deployment utility","monitoring tool","log viewer","migration tool"], ["cli"], {}, ["developer-experience","packageable"], { securityRisk: "low", scale: "small", deployments: ["package"] }),
  seed("infrastructure-operations", ["dockerized application","kubernetes service","ci-cd pipeline","terraform project","cloud deployment","monitoring system","logging stack","service-status dashboard","scheduled automation","backup utility","environment-management tool"], ["cli","api"], { backgroundJobs: true }, ["infrastructure-as-code","observable"], { securityRisk: "high", deployments: ["self-hosted","managed-cloud"] }),
];

export const PROJECT_TAXONOMY: TaxonomyEntry[] = seeds.flatMap(({ subtypes, ...common }) => subtypes.map((subtype) => ({ ...common, subtype, keywords: subtype.split(/[\s/-]+/).filter((word) => word.length > 2) })));

export function taxonomyEntryFor(text: string): { entry: TaxonomyEntry; score: number } | undefined {
  const normalized = text.toLowerCase();
  return PROJECT_TAXONOMY.map((entry) => ({ entry, score: entry.keywords.reduce((sum, word) => sum + (normalized.includes(word) ? Math.min(3, word.length / 3) : 0), normalized.includes(entry.subtype) ? 8 : 0) }))
    .sort((a, b) => b.score - a.score)[0];
}
