import { NextResponse } from "next/server";
import { createHash, timingSafeEqual } from "node:crypto";
import { mkdir, readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

const vault=path.join(process.cwd(),".foundry-data","cloud-vault");
function authorize(request:Request){const configured=process.env.FOUNDRY_CLOUD_SECRET_TOKEN||"";const supplied=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!configured||!supplied)return false;const left=createHash("sha256").update(configured).digest();const right=createHash("sha256").update(supplied).digest();return timingSafeEqual(left,right);}
function target(key:string){if(!/^[a-f0-9]{64}$/.test(key))throw new Error("Cloud secret key is invalid.");return path.join(vault,`${key}.json`);}
export async function GET(request:Request,{params}:{params:Promise<{key:string}>}){if(!authorize(request))return NextResponse.json({error:"Unauthorized"},{status:401});try{return NextResponse.json(JSON.parse(await readFile(target((await params).key),"utf8")));}catch(error){return NextResponse.json({error:(error as NodeJS.ErrnoException).code==="ENOENT"?"Not found":"Cloud vault read failed"},{status:(error as NodeJS.ErrnoException).code==="ENOENT"?404:500});}}
export async function PUT(request:Request,{params}:{params:Promise<{key:string}>}){if(!authorize(request))return NextResponse.json({error:"Unauthorized"},{status:401});try{const body=await request.json() as {envelope?:{version?:number;iv?:string;tag?:string;ciphertext?:string};scope?:Record<string,unknown>};if(body.envelope?.version!==1||![body.envelope.iv,body.envelope.tag,body.envelope.ciphertext].every(value=>typeof value==="string"&&value.length>0))throw new Error("Encrypted envelope is invalid.");await mkdir(vault,{recursive:true});const file=target((await params).key);const temporary=`${file}.${Date.now()}.tmp`;await writeFile(temporary,JSON.stringify({envelope:body.envelope,scope:body.scope}),{encoding:"utf8",mode:0o600});await rename(temporary,file);return new NextResponse(null,{status:204});}catch{return NextResponse.json({error:"Cloud vault write failed"},{status:400});}}
export async function DELETE(request:Request,{params}:{params:Promise<{key:string}>}){if(!authorize(request))return NextResponse.json({error:"Unauthorized"},{status:401});try{await unlink(target((await params).key));return new NextResponse(null,{status:204});}catch(error){return new NextResponse(null,{status:(error as NodeJS.ErrnoException).code==="ENOENT"?204:500});}}
