"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, CircleAlert, KeyRound, Loader2, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import type { IntegrationDefinition, CredentialSummary } from "@/lib/integrations/types";

type Service = { definition:IntegrationDefinition; evidence:Array<{kind:string;value:string;path?:string}>; missingEnvironment:string[]; credential?:CredentialSummary;state:string;confidence:number;used:boolean };
type Props={projectId:string;workspaceId:string;files:Array<{path:string;content?:string}>;localAgentOffline?:boolean};
const scopeFor=(projectId:string,workspaceId:string,provider:string)=>({userId:"local-user",workspaceId,projectId,environment:"development",provider,location:"local"});

export function CredentialsSettings({projectId,workspaceId,files,localAgentOffline}:Props){
 const [services,setServices]=useState<Service[]>([]),[catalog,setCatalog]=useState<IntegrationDefinition[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [selected,setSelected]=useState<IntegrationDefinition|null>(null),[values,setValues]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [catalogQuery,setCatalogQuery]=useState("");
 const inspect=useCallback(async()=>{setLoading(true);setError("");try{const [cat,res]=await Promise.all([fetch("/api/integrations/catalog").then(r=>r.json()),fetch("/api/integrations/detect",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({files,scope:{userId:"local-user",workspaceId,projectId,environment:"development",location:"local"}})}).then(r=>r.json())]);if(res.error)throw new Error(res.error);setCatalog(cat.integrations||[]);setServices(res.detected||[]);if(res.malformedEnvironmentFiles?.length)setError(`Malformed environment file entries: ${res.malformedEnvironmentFiles.map((x:{path:string})=>x.path).join(", ")}. Foundry ignored invalid lines.`);}catch(e){setError(e instanceof Error?e.message:"Project services could not be inspected.");}finally{setLoading(false);}},[files,projectId,workspaceId]);
 useEffect(()=>{void inspect();},[inspect]);
 const available=useMemo(()=>catalog.filter(item=>!services.some(service=>service.definition.id===item.id)).filter(item=>`${item.name} ${item.category} ${item.pack}`.toLowerCase().includes(catalogQuery.toLowerCase())).slice(0,60),[catalog,services,catalogQuery]);
 async function action(action:string,provider:string,extra:Record<string,unknown>={}){setBusy(true);setNotice("");try{const response=await fetch("/api/integrations/credentials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,scope:scopeFor(projectId,workspaceId,provider),...extra})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Credential operation failed.");setNotice(result.verification?.message||`${provider} credential updated.`);setSelected(null);setValues({});await inspect();}catch(e){setNotice(e instanceof Error?e.message:"Credential operation failed.");}finally{setBusy(false);}}
 async function beginOAuth(def:IntegrationDefinition){setBusy(true);try{const response=await fetch("/api/integrations/oauth/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope:scopeFor(projectId,workspaceId,def.id)})});const result=await response.json();if(!response.ok)throw new Error(result.error);window.location.assign(result.url);}catch(e){setNotice(e instanceof Error?e.message:"OAuth could not start.");setBusy(false);}}
 async function saveMetadataProfile(def:IntegrationDefinition,replace:boolean){setBusy(true);setNotice("");try{const response=await fetch("/api/integrations/profiles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scope:scopeFor(projectId,workspaceId,def.id),definition:def,values,variableMappings:Object.fromEntries(def.fields.flatMap(field=>field.env.map(name=>[field.key,name]))),replace})});const result=await response.json();if(!response.ok)throw new Error(result.error);setNotice(result.message);setSelected(null);setValues({});await inspect();}catch(e){setNotice(e instanceof Error?e.message:"Integration profile could not be saved.");}finally{setBusy(false);}}
 return <section className="grid gap-4 border-t border-overlay/10 pt-5">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-extrabold text-foundry-ink">Credentials & Integrations</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-foundry-muted">Foundry inspects project evidence, keeps secrets outside project files, and verifies every connection. Secret values are never shown again after saving.</p></div><button type="button" onClick={()=>void inspect()} className="flex items-center gap-2 rounded border border-overlay/15 px-3 py-2 text-xs font-bold text-foundry-ink"><RefreshCw size={13}/>Rescan project</button></div>
  {localAgentOffline?<div className="rounded border border-foundry-amber/30 bg-foundry-amber/10 p-3 text-xs text-foundry-amber">Local Agent is offline. Detection uses the files already loaded in Foundry; reconnect it to inspect the complete local project.</div>:null}
  {error?<div className="rounded border border-foundry-amber/30 bg-foundry-amber/10 p-3 text-xs text-foundry-amber">{error}</div>:null}{notice?<div className="rounded border border-foundry-blue/25 bg-foundry-blue/10 p-3 text-xs text-foundry-ink">{notice}</div>:null}
  {loading?<div className="flex items-center gap-2 py-6 text-xs text-foundry-muted"><Loader2 className="animate-spin" size={15}/>Inspecting dependencies, imports, source, configuration, environment references, and conventions…</div>:services.length?<div className="grid gap-2">{services.map(service=><ServiceRow key={service.definition.id} service={service} busy={busy} onSetup={()=>{setSelected(service.definition);setValues({});setNotice("");}} onRetest={()=>void action("retest",service.definition.id)} onRemove={()=>{if(window.confirm(`Remove ${service.definition.name} from this project and environment? This cannot be undone.`))void action("remove",service.definition.id,{confirmed:true});}}/>)}</div>:<div className="rounded border border-overlay/10 bg-overlay/[0.025] p-4 text-xs text-foundry-muted">No credential-backed services were detected in the currently loaded project evidence. You can connect one manually below.</div>}
  <details className="rounded border border-overlay/10 p-3"><summary className="cursor-pointer text-xs font-extrabold text-foundry-ink">Explore integration registry · {catalog.length} definitions</summary><input aria-label="Search integrations" value={catalogQuery} onChange={event=>setCatalogQuery(event.target.value)} placeholder="Search providers, platforms, tools, or packs…" className="mt-3 w-full rounded border border-overlay/15 bg-shade/50 px-3 py-2 text-xs text-foundry-ink outline-none focus:border-foundry-teal/50"/><div className="mt-3 flex flex-wrap gap-2">{available.map(def=><button key={def.id} type="button" onClick={()=>setSelected(def)} className="rounded border border-overlay/15 bg-overlay/[0.03] px-3 py-2 text-left text-xs font-bold text-foundry-muted hover:text-foundry-ink"><span>{def.name}</span><span className="ml-2 text-[9px] font-normal uppercase opacity-65">{def.certification?.certifiedAt?"Certified":def.maturity==="adapter"?"Adapter · not certified":"Metadata only"}</span></button>)}</div>{available.length===60?<p className="mt-2 text-[10px] text-foundry-subtle">Showing the first 60 matches. Refine the search to narrow the registry.</p>:null}</details>
  {selected?<SetupDialog def={selected} values={values} setValues={setValues} busy={busy} configured={Boolean(services.find(s=>s.definition.id===selected.id)?.credential)} onClose={()=>setSelected(null)} onOAuth={()=>void beginOAuth(selected)} onSave={(replace)=>selected.maturity==="metadata"?void saveMetadataProfile(selected,replace):void action("save",selected.id,{values,replace})}/>:null}
 </section>;
}
function ServiceRow({service,busy,onSetup,onRetest,onRemove}:{service:Service;busy:boolean;onSetup:()=>void;onRetest:()=>void;onRemove:()=>void}){const good=service.state==="connected";const label=service.state.replace(/-/g," ");return <div className="grid gap-3 rounded border border-overlay/10 bg-overlay/[0.025] p-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="flex min-w-0 gap-3">{good?<CheckCircle2 className="mt-0.5 shrink-0 text-foundry-teal" size={17}/>:<CircleAlert className="mt-0.5 shrink-0 text-foundry-amber" size={17}/>}<div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-extrabold text-foundry-ink">{service.definition.name}</span><span className="rounded bg-overlay/[0.06] px-1.5 py-0.5 text-[9px] font-bold uppercase text-foundry-muted">{label}</span><span className="rounded bg-overlay/[0.04] px-1.5 py-0.5 text-[9px] font-bold uppercase text-foundry-subtle">{service.definition.certification?.certifiedAt?"Certified":service.definition.maturity==="adapter"?"Adapter · not certified":"Metadata only"}</span></div><p className="mt-1 text-xs text-foundry-muted">{good?`Connected · Last verified ${new Date(service.credential!.lastVerifiedAt!).toLocaleString()}`:service.state==="not-used"?"Package is installed, but Foundry found no usage evidence.":`${service.missingEnvironment.join(", ")||"Configuration or verification is still required"}`}</p><p className="mt-1 truncate text-[10px] text-foundry-subtle">Confidence {service.confidence}% · {service.evidence.slice(0,3).map(e=>`${e.kind}: ${e.value}`).join(" · ")}</p></div></div><div className="flex gap-1">{service.credential&&service.definition.maturity==="adapter"?<button disabled={busy} onClick={onRetest} className="rounded p-2 text-foundry-muted hover:bg-overlay/[0.06]" title="Retest"><RefreshCw size={14}/></button>:null}{service.credential?<button disabled={busy} onClick={onRemove} className="rounded p-2 text-foundry-muted hover:bg-red-500/10 hover:text-red-400" title="Remove"><Trash2 size={14}/></button>:null}{service.state!=="not-used"?<button disabled={busy} onClick={onSetup} className="rounded border border-overlay/15 px-3 py-2 text-xs font-bold text-foundry-ink">{service.credential?"Rotate":"Configure"}</button>:null}</div></div>}
function SetupDialog({def,values,setValues,busy,configured,onClose,onOAuth,onSave}:{def:IntegrationDefinition;values:Record<string,string>;setValues:(v:Record<string,string>)=>void;busy:boolean;configured:boolean;onClose:()=>void;onOAuth:()=>void;onSave:(replace:boolean)=>void}){const metadata=def.maturity==="metadata";return <div className="fixed inset-0 z-50 grid place-items-center bg-black/55 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-lg border border-overlay/15 bg-foundry-surface p-5 shadow-2xl"><div className="flex gap-3"><ShieldCheck className="text-foundry-teal"/><div><h3 className="text-lg font-extrabold text-foundry-ink">{metadata?"Configure":"Connect"} {def.name}</h3><p className="mt-1 text-xs leading-5 text-foundry-muted">{def.help}</p>{metadata?<p className="mt-2 rounded border border-foundry-amber/25 bg-foundry-amber/10 p-2 text-[11px] text-foundry-amber">Metadata only · Foundry will save a project-specific mapping, not claim provider support or connection verification.</p>:null}</div></div>{def.auth==="oauth"&&!metadata?<button disabled={busy} onClick={onOAuth} className="mt-5 flex w-full items-center justify-center gap-2 rounded bg-foundry-teal px-4 py-3 text-sm font-extrabold text-slate-950"><KeyRound size={16}/>Continue securely with {def.name}</button>:<div className="mt-5 grid gap-3">{def.fields.length?def.fields.map(field=><label key={field.key} className="grid gap-1 text-xs font-bold text-foundry-muted">{field.label}{!field.required?<span className="font-normal"> (optional)</span>:null}<input type={field.secret?"password":"text"} autoComplete="off" value={values[field.key]||""} onChange={e=>setValues({...values,[field.key]:e.target.value})} placeholder={field.env.join(" or ")} className="rounded border border-overlay/15 bg-shade/60 px-3 py-2.5 text-sm font-normal text-foundry-ink outline-none focus:border-foundry-teal/50"/></label>):<p className="text-xs text-foundry-muted">This integration does not require a stored secret. Its project configuration can still be tracked.</p>}<button disabled={busy||(!def.fields.length)} onClick={()=>{if(configured&&!window.confirm(`Replace the saved ${def.name} credential?`))return;onSave(configured);}} className="mt-2 rounded bg-foundry-teal px-4 py-3 text-sm font-extrabold text-slate-950 disabled:opacity-45">{busy?"Saving…":metadata?"Save project profile":configured?"Replace and verify":"Save and verify"}</button></div>}<button type="button" onClick={onClose} className="mt-3 w-full px-4 py-2 text-xs font-bold text-foundry-muted">Cancel</button></div></div>}
