import type { IntegrationDefinition, IntegrationId } from "@/lib/integrations/types";
import { ecosystemSeeds, metadataDefinition } from "@/lib/integrations/ecosystem";
import { executableProviderDefinition } from "@/lib/integrations/provider-adapters";
import { hardwareDefinition } from "@/lib/integrations/hardware-adapters";

const f = (key: string, label: string, env: string[], required = true, secret = true) => ({ key, label, env, required, secret });
type BuiltinDefinition = Omit<IntegrationDefinition,"pack"|"authenticationMethods"|"preferredAuthenticationMethod"|"deploymentMappings"|"troubleshooting"|"maturity">;
const builtinDefinitions: BuiltinDefinition[] = [
  { id:"gmail", name:"Gmail", category:"email", auth:"oauth", oauthProvider:"google", fields:[f("accessToken","Google access token",["GMAIL_ACCESS_TOKEN"]),f("refreshToken","Google refresh token",["GMAIL_REFRESH_TOKEN"],false)], packages:["googleapis","@googleapis/gmail"], imports:["googleapis","gmail.users"], sourcePatterns:["smtp.gmail.com","GMAIL_"], configFiles:[], conventions:[], help:"Sign in with Google. Foundry never requests your Google password." },
  { id:"outlook", name:"Microsoft / Outlook", category:"email", auth:"oauth", oauthProvider:"microsoft", fields:[f("accessToken","Microsoft access token",["OUTLOOK_ACCESS_TOKEN"]),f("refreshToken","Microsoft refresh token",["OUTLOOK_REFRESH_TOKEN"],false)], packages:["@microsoft/microsoft-graph-client","@azure/msal-node"], imports:["microsoft-graph","msal"], sourcePatterns:["graph.microsoft.com","smtp.office365.com","OUTLOOK_"], configFiles:[], conventions:[], help:"Sign in with Microsoft. Foundry never requests your Microsoft password." },
  { id:"smtp", name:"Generic SMTP", category:"email", auth:"app-password", fields:[f("host","SMTP host",["SMTP_HOST"],true,false),f("port","SMTP port",["SMTP_PORT"],true,false),f("username","SMTP username",["SMTP_USERNAME","SMTP_USER"],true,false),f("password","App password / SMTP password",["SMTP_PASSWORD","SMTP_PASS"])], packages:["nodemailer","smtp-client"], imports:["nodemailer"], sourcePatterns:["SMTP_HOST","createTransport("], configFiles:[], conventions:[], help:"Use a provider-issued app password when MFA is enabled; never enter a normal account password." },
  { id:"postgresql", name:"PostgreSQL", category:"database", auth:"connection-string", fields:[f("url","Database URL",["DATABASE_URL","POSTGRES_URL"])], packages:["pg","postgres","@prisma/client"], imports:["from 'pg'","from \"pg\"","postgres("], sourcePatterns:["postgresql://","POSTGRES_URL"], configFiles:["prisma/schema.prisma"], conventions:["provider = \"postgresql\""], help:"Use a least-privilege database role and a separate database per environment." },
  { id:"mysql", name:"MySQL", category:"database", auth:"connection-string", fields:[f("url","Database URL",["DATABASE_URL","MYSQL_URL"])], packages:["mysql","mysql2"], imports:["mysql2","from 'mysql'"], sourcePatterns:["mysql://","MYSQL_URL"], configFiles:["prisma/schema.prisma"], conventions:["provider = \"mysql\""], help:"Use a least-privilege database user and TLS in production." },
  { id:"mongodb", name:"MongoDB", category:"database", auth:"connection-string", fields:[f("url","MongoDB URI",["MONGODB_URI","MONGO_URL"])], packages:["mongodb","mongoose"], imports:["mongoose","mongodb"], sourcePatterns:["mongodb://","mongodb+srv://","MONGODB_URI"], configFiles:[], conventions:[], help:"Prefer a scoped database user and an allowlisted network path." },
  { id:"redis", name:"Redis", category:"database", auth:"connection-string", fields:[f("url","Redis URL",["REDIS_URL","KV_URL"])], packages:["redis","ioredis","@upstash/redis"], imports:["ioredis","createClient"], sourcePatterns:["redis://","REDIS_URL","UPSTASH_REDIS"], configFiles:[], conventions:[], help:"Use TLS and a project-specific credential." },
  { id:"supabase", name:"Supabase", category:"backend", auth:"api-key", fields:[f("url","Project URL",["SUPABASE_URL","NEXT_PUBLIC_SUPABASE_URL"],true,false),f("key","API key",["SUPABASE_ANON_KEY","NEXT_PUBLIC_SUPABASE_ANON_KEY","SUPABASE_SERVICE_ROLE_KEY"])], packages:["@supabase/supabase-js"], imports:["@supabase/supabase-js"], sourcePatterns:["createClient(","SUPABASE_"], configFiles:["supabase/config.toml"], conventions:["supabase/functions"], help:"Use the anon key in clients; keep the service-role key server-only." },
  { id:"firebase", name:"Firebase", category:"backend", auth:"service-account", fields:[f("projectId","Project ID",["FIREBASE_PROJECT_ID"],true,false),f("apiKey","Web API key",["FIREBASE_API_KEY","NEXT_PUBLIC_FIREBASE_API_KEY"]),f("serviceAccount","Service account JSON",["FIREBASE_SERVICE_ACCOUNT"],false)], packages:["firebase","firebase-admin"], imports:["firebase/app","firebase-admin"], sourcePatterns:["FIREBASE_","initializeApp("], configFiles:["firebase.json",".firebaserc"], conventions:[], help:"Use a service account only on the server; client Firebase configuration is not an admin credential." },
  { id:"stripe", name:"Stripe", category:"payments", auth:"api-key", fields:[f("secretKey","Secret key",["STRIPE_SECRET_KEY"]),f("webhookSecret","Webhook signing secret",["STRIPE_WEBHOOK_SECRET"],false)], packages:["stripe","@stripe/stripe-js"], imports:["from 'stripe'","@stripe/stripe-js"], sourcePatterns:["STRIPE_SECRET_KEY","stripe.webhooks"], configFiles:[], conventions:[], help:"Use test-mode keys outside production and configure webhook signing separately." },
  { id:"twilio", name:"Twilio", category:"communications", auth:"api-key", fields:[f("accountSid","Account SID",["TWILIO_ACCOUNT_SID"],true,false),f("authToken","Auth token",["TWILIO_AUTH_TOKEN"]),f("from","Sender number",["TWILIO_PHONE_NUMBER"],false,false)], packages:["twilio"], imports:["twilio"], sourcePatterns:["TWILIO_"], configFiles:[], conventions:[], help:"Prefer API keys for production workloads and scope the sender by environment." },
  { id:"sendgrid", name:"SendGrid", category:"email", auth:"api-key", fields:[f("apiKey","API key",["SENDGRID_API_KEY"])], packages:["@sendgrid/mail"], imports:["@sendgrid/mail"], sourcePatterns:["SENDGRID_API_KEY"], configFiles:[], conventions:[], help:"Create a restricted Mail Send key." },
  { id:"resend", name:"Resend", category:"email", auth:"api-key", fields:[f("apiKey","API key",["RESEND_API_KEY"])], packages:["resend"], imports:["from 'resend'","from \"resend\""], sourcePatterns:["RESEND_API_KEY"], configFiles:[], conventions:[], help:"Use a project-specific API key and verify the sending domain." },
  { id:"openai", name:"OpenAI", category:"ai", auth:"api-key", fields:[f("apiKey","API key",["OPENAI_API_KEY"])], packages:["openai"], imports:["from 'openai'","from \"openai\""], sourcePatterns:["OPENAI_API_KEY","api.openai.com"], configFiles:[], conventions:[], help:"Use a project-scoped API key and set usage limits." },
  { id:"anthropic", name:"Anthropic", category:"ai", auth:"api-key", fields:[f("apiKey","API key",["ANTHROPIC_API_KEY"])], packages:["@anthropic-ai/sdk"], imports:["@anthropic-ai/sdk"], sourcePatterns:["ANTHROPIC_API_KEY","api.anthropic.com"], configFiles:[], conventions:[], help:"Use a workspace-scoped API key." },
  { id:"gemini", name:"Google Gemini", category:"ai", auth:"api-key", fields:[f("apiKey","API key",["GEMINI_API_KEY","GOOGLE_GENERATIVE_AI_API_KEY"])], packages:["@google/generative-ai","@google/genai"], imports:["@google/generative-ai","@google/genai"], sourcePatterns:["GEMINI_API_KEY","generativelanguage.googleapis.com"], configFiles:[], conventions:[], help:"Use a Google AI API key restricted to the required API." },
  { id:"github", name:"GitHub", category:"developer", auth:"oauth", oauthProvider:"github", fields:[f("accessToken","OAuth token",["GITHUB_TOKEN"])], packages:["@octokit/rest","octokit"], imports:["octokit"], sourcePatterns:["GITHUB_TOKEN","api.github.com"], configFiles:[".github/workflows"], conventions:[], help:"Prefer OAuth or a GitHub App with the minimum repository permissions." },
  { id:"slack", name:"Slack", category:"communications", auth:"oauth", oauthProvider:"slack", fields:[f("accessToken","Bot OAuth token",["SLACK_BOT_TOKEN"]),f("signingSecret","Signing secret",["SLACK_SIGNING_SECRET"],false)], packages:["@slack/web-api","@slack/bolt"], imports:["@slack/"], sourcePatterns:["SLACK_BOT_TOKEN","hooks.slack.com"], configFiles:["manifest.yml"], conventions:[], help:"Install through OAuth and grant only the bot scopes the project needs." },
];

const enrichedBuiltins:IntegrationDefinition[]=builtinDefinitions.map(item=>({...item,pack:item.category==="ai"?"ai":item.category==="payments"?"payments":item.category==="developer"||item.category==="communications"?"developer":"core",authenticationMethods:[item.auth],preferredAuthenticationMethod:item.auth,deploymentMappings:Object.fromEntries(item.fields.flatMap(field=>field.env.map(name=>[name,name]))),troubleshooting:["Confirm the credential belongs to the active project and environment.","Check provider permissions, expiry, network access, and account status."],maturity:"adapter",executionKind:"credential"}));
const ids=new Set(enrichedBuiltins.map(item=>item.id));
const definitions:IntegrationDefinition[]=[...new Map([...enrichedBuiltins,...ecosystemSeeds.map(metadataDefinition).filter(item=>!ids.has(item.id))].map(item=>{const executable=executableProviderDefinition(item.id);return[item.id,hardwareDefinition(executable?{...item,...executable}:item)]})).values()];

export const integrationCatalog = definitions;
export function integrationById(id: string) { return definitions.find((item) => item.id === id); }
export function publicCatalog() { return definitions.map((item) => ({ id:item.id,name:item.name,category:item.category,pack:item.pack,auth:item.auth,authenticationMethods:item.authenticationMethods,preferredAuthenticationMethod:item.preferredAuthenticationMethod,oauthProvider:item.oauthProvider,fields:item.fields,configurationFiles:item.configFiles,environmentVariables:item.fields.flatMap(field=>field.env),deploymentMappings:item.deploymentMappings,setupDocumentation:item.help,troubleshooting:item.troubleshooting,maturity:item.maturity,executionKind:item.executionKind,localAgentTest:item.localAgentTest,hostingDeploymentWriter:item.hostingDeploymentWriter,certification:item.certification })); }
export const integrationIds = new Set<IntegrationId>(definitions.map((item) => item.id));
