import "server-only";
import { integrationById } from "@/lib/integrations/catalog";
import { adapterRegistry } from "@/lib/integrations/adapter-registry";
import type { IntegrationSupportLevel } from "@/lib/integrations/types";

export type E2EManifest={provider:string;requiredCredentials:string[];testEnvironment:"sandbox"|"live";setupPrerequisites:string[];safeTestAction:string;expectedResponse:string;cleanupAction:string;failureCases:string[];rateLimitBehavior:string;revocationBehavior:string};
export type E2EResult={provider:string;level:IntegrationSupportLevel;status:"passed"|"failed"|"unavailable";message:string;ranAt:string};
export function e2eManifest(provider:string,environment:"sandbox"|"live"="sandbox"):E2EManifest{const definition=integrationById(provider);if(!definition||!adapterRegistry.has(provider))throw new Error("An executable adapter is required before creating E2E certification evidence.");return{provider,requiredCredentials:definition.fields.filter(field=>field.required).flatMap(field=>field.env.slice(0,1)),testEnvironment:environment,setupPrerequisites:["A dedicated least-privilege test account","Provider test or sandbox mode where available","Explicit permission to perform the safe validation action"],safeTestAction:"Run the adapter's authenticated, read-only account or health operation.",expectedResponse:"Provider accepts authentication and returns its documented success response.",cleanupAction:"No cleanup is required for the read-only validation action.",failureCases:["Invalid credential","Expired credential","Revoked credential","Wrong project or environment","Network or rate-limit failure"],rateLimitBehavior:"Honor Retry-After when provided; do not retry more than once in a certification run.",revocationBehavior:"Revoke the test credential, require a revoked or failed result, then replace it before further runs."};}
export async function runProviderE2E(provider:string,environment:"sandbox"|"live"="sandbox",source:Record<string,string|undefined>=process.env):Promise<E2EResult>{e2eManifest(provider,environment);const definition=integrationById(provider)!;const values:Record<string,string>={};for(const field of definition.fields){const name=field.env.find(env=>source[env]);if(name)values[field.key]=String(source[name]);}const missing=definition.fields.filter(field=>field.required&&!values[field.key]);if(missing.length)return{provider,level:"Runtime executable",status:"unavailable",message:`Executable but not live-certified. Missing test credential variables: ${missing.flatMap(field=>field.env.slice(0,1)).join(", ")}.`,ranAt:new Date().toISOString()};const result=await adapterRegistry.get(provider)!.test(values);return{provider,level:result.ok?(environment==="sandbox"?"Sandbox E2E validated":"Production certified"):"Runtime executable",status:result.ok?"passed":"failed",message:result.message,ranAt:new Date().toISOString()};}
