import type { IntegrationDefinition } from "@/lib/integrations/types";

const families=[
 {id:"pax",terms:["pax","vid_2fb8"],packages:["pax-poslink","poslink"]},{id:"verifone",terms:["verifone","vid_11ca"],packages:["verifone"]},
 {id:"id-tech",terms:["id tech","idtech","vid_0acd"],packages:["idtech"]},{id:"ingenico",terms:["ingenico","vid_079b"],packages:["ingenico"]},
 {id:"magtek",terms:["magtek","vid_0801"],packages:["magtek"]},{id:"miura",terms:["miura","vid_2a19"],packages:["miura"]},
 {id:"dejavoo",terms:["dejavoo"],packages:["dejavoo"]},{id:"castles",terms:["castles technology"],packages:["castles"]},
 {id:"newland",terms:["newland"],packages:["newland"]},{id:"clover",terms:["clover","vid_28e9"],packages:["clover-ecomm-sdk"]},
 {id:"square-terminal",terms:["square terminal"],packages:["square"]},{id:"stripe-terminal",terms:["stripe reader","stripe terminal"],packages:["@stripe/terminal-js"]},
 {id:"adyen-terminal",terms:["adyen","adyen terminal"],packages:["@adyen/api-library"]},
] as const;
export const hardwareAdapterIds=families.map(item=>item.id);
export function hardwareDefinition(definition:IntegrationDefinition):IntegrationDefinition{const family=families.find(item=>item.id===definition.id);return family?{...definition,packages:[...new Set([...definition.packages,...family.packages])],imports:[...new Set([...definition.imports,...family.packages])],sourcePatterns:[...new Set([...definition.sourcePatterns,...family.terms])],authenticationMethods:["local-provider"],preferredAuthenticationMethod:"local-provider",auth:"local-provider",help:`Foundry detects ${definition.name} SDKs and asks the Local Agent to discover devices, transport permissions, identifiers, and driver state. Hardware and processor certification still requires a real device.`,maturity:"adapter",executionKind:"hardware",localAgentTest:true}:definition;}
export async function diagnoseHardware(provider:string,agent:{url:string;token?:string}){const family=families.find(item=>item.id===provider);if(!family)throw new Error("Unknown payment hardware family.");const url=new URL(agent.url);if(url.protocol!=="http:"||!["127.0.0.1","localhost","::1"].includes(url.hostname))throw new Error("Hardware discovery requires a loopback Local Agent.");const response=await fetch(`${agent.url.replace(/\/$/,"")}/hardware/discover`,{method:"POST",headers:{"content-type":"application/json",...(agent.token?{authorization:`Bearer ${agent.token}`}:{})},body:"{}"});if(!response.ok)throw new Error("Local Agent hardware diagnostics are unavailable.");const payload=await response.json() as {devices?:Array<{name:string;id:string;status:string}>};const matches=(payload.devices||[]).filter(device=>family.terms.some(term=>`${device.name} ${device.id}`.toLowerCase().includes(term)));return{provider,detected:matches.length>0,devices:matches.map(item=>({name:item.name,id:item.id,status:item.status})),hardwareValidated:false,message:matches.length?"A matching device was discovered. Production certification still requires processor and transaction testing.":"No matching attached device was discovered."};}
