import { afterEach, describe, expect, it, vi } from "vitest";
import { detectProjectIntegrations } from "@/lib/integrations/detection";
import { integrationById } from "@/lib/integrations/catalog";
import { verifyCredential } from "@/lib/integrations/adapters";
import { redactSensitiveData, redactSensitiveText } from "@/lib/security/secret-redaction";
import { integrationCatalog } from "@/lib/integrations/catalog";
import { certificationProgress, IntegrationRegistry } from "@/lib/integrations/registry";
import { certifyIntegration, integrationLabel, integrationSupportLevel } from "@/lib/integrations/certification";
import { serviceState } from "@/lib/integrations/health";
import { adapterRegistry } from "@/lib/integrations/adapter-registry";
import { createRequire } from "node:module";
import { providerAdapterSpecs, providerRequestDescriptor, verifyProviderAdapter } from "@/lib/integrations/provider-adapters";
import { e2eManifest, runProviderE2E } from "@/lib/integrations/e2e-harness";
import { hardwareAdapterIds } from "@/lib/integrations/hardware-adapters";
import { writeHostingSecret } from "@/lib/integrations/deployment-writers";

afterEach(()=>vi.restoreAllMocks());
describe("project service detection",()=>{
 it("detects dependencies, imports, source, config, env references and conventions",()=>{const result=detectProjectIntegrations([{path:"package.json",content:JSON.stringify({dependencies:{stripe:"1",nodemailer:"1","@prisma/client":"1"}})},{path:"src/mail.ts",content:"import nodemailer from 'nodemailer'; process.env.SMTP_PASSWORD"},{path:"prisma/schema.prisma",content:'provider = "postgresql"\nurl = env("DATABASE_URL")'},{path:".env",content:"SMTP_HOST=x\nSMTP_PORT=587\nSMTP_USERNAME=u\n"}]);expect(result.detected.map(x=>x.definition.id)).toEqual(expect.arrayContaining(["smtp","postgresql","stripe"]));expect(result.detected.find(x=>x.definition.id==="smtp")?.missingEnvironment).toContain("SMTP_PASSWORD");});
 it("reports malformed environment files without reading secret values",()=>{const result=detectProjectIntegrations([{path:".env",content:"NOT VALID\nOPENAI_API_KEY=highly-confidential-value"},{path:"ai.ts",content:"process.env.OPENAI_API_KEY"}]);expect(result.malformedEnvironmentFiles[0].lines).toEqual(["line 1"]);expect(JSON.stringify(result)).not.toContain("highly-confidential-value");});
 it("keeps optional credentials optional",()=>{const result=detectProjectIntegrations([{path:"package.json",content:JSON.stringify({dependencies:{stripe:"1"}})}]);expect(result.detected.find(x=>x.definition.id==="stripe")?.missingEnvironment).not.toContain("STRIPE_WEBHOOK_SECRET");});
 it("does not treat an installed but unused package as active",()=>{const result=detectProjectIntegrations([{path:"package.json",content:JSON.stringify({dependencies:{stripe:"1"}})}]);expect(result.detected.find(x=>x.definition.id==="stripe")).toMatchObject({used:false,state:"not-used"});});
 it("detects non-JavaScript manifests and infrastructure files",()=>{const result=detectProjectIntegrations([{path:"requirements.txt",content:"sentry-sdk==2.0"},{path:"app.py",content:"import sentry_sdk\nos.getenv('SENTRY_DSN')"},{path:"Dockerfile",content:"FROM node:22"},{path:"infra/main.tf",content:'provider "aws" {}'}]);expect(result.detected.some(x=>x.definition.name==="Sentry")).toBe(true);expect(result.detected.some(x=>x.definition.name==="Terraform")).toBe(true);});
 it("creates a generic profile for an undocumented used SDK",()=>{const result=detectProjectIntegrations([{path:"package.json",content:JSON.stringify({dependencies:{"acme-mystery-sdk":"1"}})},{path:"src/acme.ts",content:"import Acme from 'acme-mystery-sdk'; new Acme(process.env.ACME_PRIVATE_TOKEN)"}]);const unknown=result.detected.find(x=>x.definition.id==="project-acme-mystery-sdk");expect(unknown).toMatchObject({state:"credentials-required",used:true});expect(unknown?.definition.fields[0].env).toEqual(["ACME_PRIVATE_TOKEN"]);});
});
describe("support matrix evidence",()=>{it("reports runtime injection for executable credential adapters",()=>{const require=createRequire(import.meta.url);const {statusFor}=require("../../scripts/generate-integration-support-matrix.cjs") as {statusFor:(definition:Record<string,unknown>)=>{runtime:string}};expect(statusFor({maturity:"adapter",fields:[{key:"apiKey"}]}).runtime).toContain("Fully implemented");expect(statusFor({maturity:"metadata",fields:[{key:"apiKey"}]}).runtime).toContain("Partially implemented");});});
describe("executable provider batch",()=>{
 it("registers at least 85 total executable adapters with concrete credential schemas",()=>{expect(adapterRegistry.list().length).toBeGreaterThanOrEqual(85);for(const spec of providerAdapterSpecs){expect(adapterRegistry.has(spec.id)).toBe(true);expect(integrationById(spec.id)?.maturity).toBe("adapter");expect(spec.fields.length).toBeGreaterThan(0);expect(spec.fields.every(item=>item.env.length>0)).toBe(true);}});
 it.each(providerAdapterSpecs.filter(item=>!["amazon-ses","amazon-cognito","nextauth-auth-js","passport-js","sqlite","microsoft-sql-server","oracle","cockroachdb","neon","planetscale","dynamodb","firestore","cosmos-db","aws"].includes(item.id)))("performs an authenticated provider request for $id",async spec=>{const fetchMock=vi.fn().mockResolvedValue(new Response("{}",{status:200}));vi.stubGlobal("fetch",fetchMock);const values=Object.fromEntries(spec.fields.map(item=>[item.key,/(?:url|issuer)/i.test(item.key)?"https://provider.test":`${item.key}-test-value`]));expect((await verifyProviderAdapter(spec.id,values)).ok).toBe(true);const [url,init]=fetchMock.mock.calls[0] as [string,RequestInit|undefined];expect(url).toMatch(/^https:\/\//);expect(Object.keys((init?.headers||{}) as Record<string,string>).length>0||url.includes("test-value")).toBe(true);});
});
describe("execution foundations",()=>{
 it("builds a Local Agent request without executing it on the Foundry server",async()=>{const descriptor=await providerRequestDescriptor("openai" as never,{apiKey:"unused"}).catch(()=>undefined);expect(descriptor).toBeUndefined();const mailgun=await providerRequestDescriptor("mailgun",{apiKey:"secret",domain:"example.test"});expect(mailgun.url).toContain("mailgun.net");expect(mailgun.headers.authorization).toMatch(/^Basic /);});
 it("writes encrypted hosting variables through real provider endpoints",async()=>{const request=vi.fn().mockResolvedValue(new Response("{}",{status:200}));vi.stubGlobal("fetch",request);await writeHostingSecret({provider:"vercel",projectId:"project"},{token:"hosting-token"},"OPENAI_API_KEY","project-secret");expect(request).toHaveBeenCalledWith(expect.stringContaining("/v10/projects/project/env"),expect.objectContaining({method:"POST"}));expect(JSON.parse(String(request.mock.calls[0][1].body))).toMatchObject({key:"OPENAI_API_KEY",value:"project-secret",type:"encrypted"});});
 it("defines all eight certification levels without promoting unavailable accounts",async()=>{expect(integrationSupportLevel(integrationById("openai")!)).toBe("Runtime executable");expect(integrationSupportLevel(integrationById("openai")!,{sandboxE2E:true})).toBe("Sandbox E2E validated");expect(e2eManifest("openai").failureCases).toContain("Revoked credential");expect(await runProviderE2E("openai","sandbox",{})).toMatchObject({status:"unavailable",level:"Runtime executable"});});
 it("registers payment hardware diagnostics without claiming hardware validation",()=>{expect(hardwareAdapterIds).toHaveLength(13);for(const id of hardwareAdapterIds){expect(integrationById(id)?.maturity).toBe("adapter");expect(integrationById(id)?.certification).toBeUndefined();}});
 it("detects a licensed hardware SDK already present in an opened project by its artifact path",()=>{const result=detectProjectIntegrations([{path:"app/libs/PAX-POSLink-Android.aar"}]);const pax=result.detected.find(item=>item.definition.id==="pax");expect(pax).toMatchObject({used:true,required:true});expect(pax?.evidence[0].path).toBe("app/libs/PAX-POSLink-Android.aar");});
});
describe("connection adapters",()=>{
 it("accepts a successful API connection",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response("{}",{status:200})));expect((await verifyCredential(integrationById("openai")!,{apiKey:"test"})).ok).toBe(true);});
 it("classifies expired credentials",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response('{"error":"token expired"}',{status:401})));expect((await verifyCredential(integrationById("openai")!,{apiKey:"test"})).status).toBe("expired");});
 it("classifies revoked credentials",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response('{"error":"revoked"}',{status:401})));expect((await verifyCredential(integrationById("github")!,{accessToken:"test"})).status).toBe("revoked");});
 it("returns a recoverable failure without leaking provider or network error details",async()=>{vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("offline with secret-token")));const result=await verifyCredential(integrationById("resend")!,{apiKey:"test"});expect(result).toMatchObject({ok:false,status:"failed"});expect(result.message).not.toContain("secret-token");expect(result.message).toContain("Check the credential");});
});
describe("secret masking",()=>{it("redacts errors, tool output and nested telemetry",()=>{expect(redactSensitiveText("OPENAI_API_KEY=sk-proj-abcdefghijklmnopqrstuvwxyz")).not.toContain("abcdefghijklmnopqrstuvwxyz");expect(redactSensitiveData({authorization:"Bearer abc",nested:{password:"hello"}})).toEqual({authorization:"[REDACTED]",nested:{password:"[REDACTED]"}});});});
describe("extensible registry and certification",()=>{
 it("loads the full ecosystem with unique ids",()=>{expect(integrationCatalog.length).toBeGreaterThan(200);expect(new Set(integrationCatalog.map(item=>item.id)).size).toBe(integrationCatalog.length);});
 it("loads and disables packs dynamically",()=>{const registry=new IntegrationRegistry();const before=registry.definitions().length;const pack=registry.listPacks().find(item=>item.id==="analytics")!;expect(pack.integrationCount).toBeGreaterThan(5);registry.setPackEnabled("analytics",false);expect(registry.definitions().length).toBeLessThan(before);});
 it("never labels incomplete evidence as certified",()=>{const openai=integrationById("openai")!;expect(certificationProgress(openai).certified).toBe(false);expect(integrationLabel(openai)).toContain("not certified");expect(()=>certifyIntegration(openai,{checks:{security:{passedAt:new Date().toISOString(),suite:"security"}},certifiedAt:new Date().toISOString()})).toThrow("missing passing evidence");});
 it("keeps metadata definitions out of the executable adapter registry",()=>{expect(adapterRegistry.has("openai")).toBe(true);expect(adapterRegistry.has("adyen")).toBe(false);expect(integrationById("adyen")?.maturity).toBe("metadata");});
 it("derives lifecycle state from verified credential health",()=>{const detected=detectProjectIntegrations([{path:"x.ts",content:"process.env.OPENAI_API_KEY"}]).detected[0];const base={provider:"openai",scope:{userId:"u",workspaceId:"w",projectId:"p",environment:"test",provider:"openai",location:"local" as const},fields:{},createdAt:"x",updatedAt:"x"};expect(serviceState(detected,{...base,status:"expired"})).toBe("credential-expired");expect(serviceState(detected,{...base,status:"revoked"})).toBe("credential-revoked");expect(serviceState(detected,{...base,status:"configured",lastVerifiedAt:"x"})).toBe("connected");});
});
