import "server-only";
import { integrationById } from "@/lib/integrations/catalog";
import { adapterRegistry } from "@/lib/integrations/adapter-registry";
import { credentialSummary, getCredential, removeCredential, saveCredential, updateCredentialStatus } from "@/lib/integrations/secret-store";
import type { CredentialScope } from "@/lib/integrations/types";
import { redactSensitiveText } from "@/lib/security/secret-redaction";
import { appendJournalEntry } from "@/lib/factory/runtime";
import { refreshOAuth, revokeOAuth } from "@/lib/integrations/oauth";
import { writeHostingSecret, type HostingTarget } from "@/lib/integrations/deployment-writers";
import { providerRequestDescriptor } from "@/lib/integrations/provider-adapters";

async function journal(scope:CredentialScope,title:string,status:"completed"|"warning"|"error",details:Record<string,string|boolean|undefined>={}){await appendJournalEntry(scope.projectId,{id:`integration-${Date.now()}`,timestamp:new Date().toISOString(),kind:status==="error"?"blocked":"inspection",status,title,details:{provider:scope.provider,environment:scope.environment,location:scope.location,...details}}).catch(()=>undefined);}

export function normalizeScope(input:Partial<CredentialScope>):CredentialScope { const providerId=String(input.provider||"");const provider=integrationById(providerId);if(!provider&&!/^project-[a-z0-9-]+$/.test(providerId))throw new Error("Unknown integration provider."); const clean=(value:unknown,name:string)=>{const result=String(value||"").trim();if(!result||result.length>160||!/^[a-zA-Z0-9._:@/-]+$/.test(result))throw new Error(`${name} is required.`);return result;}; return {userId:clean(input.userId,"User id"),workspaceId:clean(input.workspaceId,"Workspace id"),projectId:clean(input.projectId,"Project id"),environment:clean(input.environment,"Environment"),provider:provider?.id||providerId,location:input.location==="cloud"?"cloud":"local"}; }
export function validateValues(scope:CredentialScope,values:Record<string,unknown>){const def=integrationById(scope.provider);const output:Record<string,string>={};if(!def){for(const [key,item]of Object.entries(values)){if(typeof item==="string"&&item.trim())output[key]=item.trim();}if(!Object.keys(output).length)throw new Error("No credential values were provided.");return output;}for(const field of def.fields){const value=typeof values[field.key]==="string"?String(values[field.key]).trim():"";if(field.required&&!value)throw new Error(`${field.label} is required.`);if(value)output[field.key]=value;}if(!Object.keys(output).length)throw new Error("No credential values were provided.");return output;}
export async function connectCredential(scope:CredentialScope,values:Record<string,unknown>,replace:boolean,verify=true){const def=integrationById(scope.provider);const adapter=adapterRegistry.get(scope.provider);const safe=validateValues(scope,values);const saved=await saveCredential(scope,safe,replace);if(!verify||!def||!adapter){await journal(scope,`${def?.name||scope.provider} credential stored`,"warning",{verification:adapter?"pending":"generic-profile"});return {credential:saved,verification:null};}const result=await adapter.test(safe);const credential=await updateCredentialStatus(scope,result.status,result.ok?undefined:redactSensitiveText(result.message));await journal(scope,`${def.name} ${replace?"credential rotated":"connected"}`,result.ok?"completed":"error",{verification:result.status});return {credential,verification:{...result,message:redactSensitiveText(result.message)}};}
export async function retestCredential(scope:CredentialScope){const def=integrationById(scope.provider)!;const adapter=adapterRegistry.get(scope.provider);if(!adapter)throw new Error("This integration has metadata but no connection adapter. It cannot be retested or labeled connected.");const record=await getCredential(scope);if(!record)throw new Error("Credential is not configured for this project and environment.");const result=await adapter.healthCheck(record.values);await journal(scope,`${def.name} connection retested`,result.ok?"completed":"error",{verification:result.status});return {credential:await updateCredentialStatus(scope,result.status,result.ok?undefined:redactSensitiveText(result.message)),verification:{...result,message:redactSensitiveText(result.message)}};}
export async function retestCredentialWithLocalAgent(scope:CredentialScope,agent:{url:string;token?:string}){const record=await getCredential(scope);if(!record)throw new Error("Credential is not configured for this project and environment.");const url=new URL(agent.url);if(url.protocol!=="http:"||!["127.0.0.1","localhost","::1"].includes(url.hostname))throw new Error("Local Agent integration tests require a loopback HTTP endpoint.");const probe=await providerRequestDescriptor(scope.provider,record.values);const response=await fetch(`${agent.url.replace(/\/$/,"")}/integrations/probe`,{method:"POST",headers:{"content-type":"application/json",...(agent.token?{authorization:`Bearer ${agent.token}`}:{})},body:JSON.stringify({probe})});const result=await response.json() as {ok:boolean;status:"configured"|"expired"|"revoked"|"failed";message:string};if(!response.ok)throw new Error("The Local Agent integration test endpoint is unavailable.");await journal(scope,`${integrationById(scope.provider)?.name||scope.provider} tested through Local Agent`,result.ok?"completed":"error",{verification:result.status});return{credential:await updateCredentialStatus(scope,result.status,result.ok?undefined:redactSensitiveText(result.message)),verification:{...result,message:redactSensitiveText(result.message)}};}
export async function deleteCredential(scope:CredentialScope,confirmed:boolean){const removed=await removeCredential(scope,confirmed);await journal(scope,`${integrationById(scope.provider)!.name} credential removed`,"completed");return removed;}
export async function getCredentialSummary(scope:CredentialScope){return credentialSummary(scope);}
export async function renewOAuthCredential(scope:CredentialScope){const def=integrationById(scope.provider);const record=await getCredential(scope);if(!def?.oauthProvider||!record)throw new Error("OAuth credential is not configured for this scope.");const renewed=await refreshOAuth(def,record.values.refreshToken);return connectCredential(scope,{...record.values,...renewed},true,true);}
export async function revokeOAuthCredential(scope:CredentialScope,confirmed:boolean){const def=integrationById(scope.provider);const record=await getCredential(scope);if(!def?.oauthProvider||!record)throw new Error("OAuth credential is not configured for this scope.");await revokeOAuth(def,record.values.accessToken,confirmed);await journal(scope,`${def.name} OAuth grant revoked`,"completed");return removeCredential(scope,true);}
export async function deploymentEnvironment(scope:CredentialScope,approved:boolean){if(!approved){await journal(scope,"Deployment secret injection denied","warning");throw new Error("Deployment secret injection requires explicit permission.");}const def=integrationById(scope.provider)!;const record=await getCredential(scope);if(!record||record.status!=="configured")throw new Error("Only a verified credential can be injected into deployment.");const environment:Record<string,string>={};for(const field of def.fields){if(record.values[field.key]&&field.env[0])environment[field.env[0]]=record.values[field.key];}await journal(scope,`${def.name} prepared for deployment injection`,"completed",{variables:Object.keys(environment).join(", ")});return {names:Object.keys(environment),inject:async(writer:(name:string,value:string)=>Promise<void>)=>{for(const [name,value]of Object.entries(environment))await writer(name,value);}};}
export async function deployCredentialToHosting(sourceScope:CredentialScope,targetScope:CredentialScope,target:HostingTarget,approved:boolean){const deployment=await deploymentEnvironment(sourceScope,approved);const hosting=await getCredential(targetScope);if(!hosting||hosting.status!=="configured"||targetScope.provider!==target.provider)throw new Error("The hosting provider must be connected and verified in the same project scope.");await deployment.inject((name,value)=>writeHostingSecret(target,hosting.values,name,value));await journal(sourceScope,`${integrationById(sourceScope.provider)?.name||sourceScope.provider} injected into ${target.provider}`,"completed",{variables:deployment.names.join(", ")});return deployment.names;}
