import "server-only";
import { createHmac } from "node:crypto";
import { AsyncLocalStorage } from "node:async_hooks";
import type { AuthenticationMethod, CredentialField } from "@/lib/integrations/types";
import type { VerificationResult } from "@/lib/integrations/adapters";

const field=(key:string,label:string,env:string[],secret=true,required=true):CredentialField=>({key,label,env,secret,required});
export type ProviderAdapterSpec={id:string;auth:AuthenticationMethod;fields:CredentialField[];verify:(values:Record<string,string>)=>Promise<Response>};
const bearer=(token:string)=>({authorization:`Bearer ${token}`});
const basic=(user:string,password:string)=>({authorization:`Basic ${Buffer.from(`${user}:${password}`).toString("base64")}`});
const requestContext=new AsyncLocalStorage<typeof fetch>();
const request=(input:RequestInfo|URL,init?:RequestInit)=>(requestContext.getStore()||fetch)(input,init);
const get=(url:string,headers:Record<string,string>={})=>request(url,{headers,cache:"no-store"});

export const providerAdapterSpecs:ProviderAdapterSpec[]=[
 {id:"mailgun",auth:"api-key",fields:[field("apiKey","Private API key",["MAILGUN_API_KEY"]),field("domain","Sending domain",["MAILGUN_DOMAIN"],false)],verify:v=>get("https://api.mailgun.net/v3/domains",basic("api",v.apiKey))},
 {id:"postmark",auth:"api-key",fields:[field("serverToken","Server API token",["POSTMARK_SERVER_TOKEN"])],verify:v=>get("https://api.postmarkapp.com/server",{"X-Postmark-Server-Token":v.serverToken,accept:"application/json"})},
 {id:"mailjet",auth:"api-key",fields:[field("apiKey","API key",["MAILJET_API_KEY"]),field("secretKey","Secret key",["MAILJET_SECRET_KEY"])],verify:v=>get("https://api.mailjet.com/v3/REST/myprofile",basic(v.apiKey,v.secretKey))},
 {id:"brevo",auth:"api-key",fields:[field("apiKey","API key",["BREVO_API_KEY"])],verify:v=>get("https://api.brevo.com/v3/account",{"api-key":v.apiKey,accept:"application/json"})},
 {id:"sparkpost",auth:"api-key",fields:[field("apiKey","API key",["SPARKPOST_API_KEY"])],verify:v=>get("https://api.sparkpost.com/api/v1/account",{authorization:v.apiKey,accept:"application/json"})},
 {id:"vonage",auth:"api-key",fields:[field("apiKey","API key",["VONAGE_API_KEY"]),field("apiSecret","API secret",["VONAGE_API_SECRET"])],verify:v=>get(`https://rest.nexmo.com/account/get-balance?api_key=${encodeURIComponent(v.apiKey)}&api_secret=${encodeURIComponent(v.apiSecret)}`)},
 {id:"telnyx",auth:"api-key",fields:[field("apiKey","API key",["TELNYX_API_KEY"])],verify:v=>get("https://api.telnyx.com/v2/balance",bearer(v.apiKey))},
 {id:"plivo",auth:"api-key",fields:[field("authId","Auth ID",["PLIVO_AUTH_ID"],false),field("authToken","Auth token",["PLIVO_AUTH_TOKEN"])],verify:v=>get(`https://api.plivo.com/v1/Account/${encodeURIComponent(v.authId)}/`,basic(v.authId,v.authToken))},
 {id:"discord",auth:"access-token",fields:[field("botToken","Bot token",["DISCORD_BOT_TOKEN"])],verify:v=>get("https://discord.com/api/v10/users/@me",{authorization:`Bot ${v.botToken}`})},
 {id:"microsoft-teams",auth:"access-token",fields:[field("accessToken","Microsoft Graph access token",["TEAMS_ACCESS_TOKEN"])],verify:v=>get("https://graph.microsoft.com/v1.0/me/joinedTeams",bearer(v.accessToken))},
 {id:"pusher",auth:"signed-credential",fields:[field("appId","App ID",["PUSHER_APP_ID"],false),field("key","Key",["PUSHER_KEY"],false),field("secret","Secret",["PUSHER_SECRET"]),field("cluster","Cluster",["PUSHER_CLUSTER"],false)],verify:v=>{const timestamp=Math.floor(Date.now()/1000);const query=`auth_key=${encodeURIComponent(v.key)}&auth_timestamp=${timestamp}&auth_version=1.0`;const signature=createHmac("sha256",v.secret).update(`GET\n/apps/${v.appId}/channels\n${query}`).digest("hex");return get(`https://api-${encodeURIComponent(v.cluster)}.pusher.com/apps/${encodeURIComponent(v.appId)}/channels?${query}&auth_signature=${signature}`);}},
 {id:"ably",auth:"api-key",fields:[field("apiKey","API key",["ABLY_API_KEY"])],verify:v=>get("https://rest.ably.io/stats?limit=1",basic(v.apiKey,""))},
 {id:"onesignal",auth:"api-key",fields:[field("appId","App ID",["ONESIGNAL_APP_ID"],false),field("restApiKey","REST API key",["ONESIGNAL_REST_API_KEY"])],verify:v=>get(`https://api.onesignal.com/apps/${encodeURIComponent(v.appId)}`,{authorization:`Key ${v.restApiKey}`})},
 {id:"firebase-cloud-messaging",auth:"access-token",fields:[field("projectId","Project ID",["FIREBASE_PROJECT_ID"],false),field("accessToken","Google OAuth access token",["FIREBASE_ACCESS_TOKEN"])],verify:v=>get(`https://firebase.googleapis.com/v1beta1/projects/${encodeURIComponent(v.projectId)}`,bearer(v.accessToken))},
 {id:"amazon-ses",auth:"signed-credential",fields:[field("accessKeyId","Access key ID",["AWS_ACCESS_KEY_ID"],false),field("secretAccessKey","Secret access key",["AWS_SECRET_ACCESS_KEY"]),field("region","Region",["AWS_REGION"],false),field("sessionToken","Session token",["AWS_SESSION_TOKEN"],true,false)],verify:async v=>{const {SESv2Client,GetAccountCommand}=await import("@aws-sdk/client-sesv2");const client=new SESv2Client({region:v.region,credentials:{accessKeyId:v.accessKeyId,secretAccessKey:v.secretAccessKey,...(v.sessionToken?{sessionToken:v.sessionToken}:{})}});try{await client.send(new GetAccountCommand({}));return new Response("{}",{status:200});}finally{client.destroy();}}},
 {id:"auth0",auth:"access-token",fields:[field("issuerUrl","Issuer URL",["AUTH0_ISSUER_BASE_URL"],false),field("accessToken","Management API access token",["AUTH0_ACCESS_TOKEN"])],verify:v=>get(`${v.issuerUrl.replace(/\/$/,"")}/userinfo`,bearer(v.accessToken))},
 {id:"clerk",auth:"api-key",fields:[field("secretKey","Secret key",["CLERK_SECRET_KEY"])],verify:v=>get("https://api.clerk.com/v1/users?limit=1",bearer(v.secretKey))},
 {id:"supabase-auth",auth:"api-key",fields:[field("url","Project URL",["SUPABASE_URL"],false),field("serviceRoleKey","Service role key",["SUPABASE_SERVICE_ROLE_KEY"])],verify:v=>get(`${v.url.replace(/\/$/,"")}/auth/v1/admin/users?page=1&per_page=1`,{apikey:v.serviceRoleKey,authorization:`Bearer ${v.serviceRoleKey}`})},
 {id:"firebase-authentication",auth:"access-token",fields:[field("projectId","Project ID",["FIREBASE_PROJECT_ID"],false),field("accessToken","Google OAuth access token",["FIREBASE_ACCESS_TOKEN"])],verify:v=>get(`https://identitytoolkit.googleapis.com/v1/projects/${encodeURIComponent(v.projectId)}/config`,bearer(v.accessToken))},
 {id:"amazon-cognito",auth:"signed-credential",fields:[field("accessKeyId","Access key ID",["AWS_ACCESS_KEY_ID"],false),field("secretAccessKey","Secret access key",["AWS_SECRET_ACCESS_KEY"]),field("region","Region",["AWS_REGION"],false),field("sessionToken","Session token",["AWS_SESSION_TOKEN"],true,false)],verify:async v=>{const {CognitoIdentityProviderClient,ListUserPoolsCommand}=await import("@aws-sdk/client-cognito-identity-provider");const client=new CognitoIdentityProviderClient({region:v.region,credentials:{accessKeyId:v.accessKeyId,secretAccessKey:v.secretAccessKey,...(v.sessionToken?{sessionToken:v.sessionToken}:{})}});try{await client.send(new ListUserPoolsCommand({MaxResults:1}));return new Response("{}",{status:200});}finally{client.destroy();}}},
 {id:"microsoft-entra-id",auth:"access-token",fields:[field("accessToken","Microsoft Graph access token",["ENTRA_ACCESS_TOKEN"])],verify:v=>get("https://graph.microsoft.com/v1.0/organization",bearer(v.accessToken))},
 {id:"okta",auth:"api-key",fields:[field("domain","Okta domain",["OKTA_DOMAIN"],false),field("apiToken","API token",["OKTA_API_TOKEN"])],verify:v=>get(`https://${v.domain.replace(/^https?:\/\//,"").replace(/\/$/,"")}/api/v1/users?limit=1`,{authorization:`SSWS ${v.apiToken}`,accept:"application/json"})},
 {id:"workos",auth:"api-key",fields:[field("apiKey","API key",["WORKOS_API_KEY"])],verify:v=>get("https://api.workos.com/organizations?limit=1",bearer(v.apiKey))},
 {id:"keycloak",auth:"username-password",fields:[field("baseUrl","Keycloak URL",["KEYCLOAK_URL"],false),field("realm","Realm",["KEYCLOAK_REALM"],false),field("clientId","Client ID",["KEYCLOAK_CLIENT_ID"],false),field("clientSecret","Client secret",["KEYCLOAK_CLIENT_SECRET"])],verify:v=>request(`${v.baseUrl.replace(/\/$/,"")}/realms/${encodeURIComponent(v.realm)}/protocol/openid-connect/token`,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"client_credentials",client_id:v.clientId,client_secret:v.clientSecret})})},
 {id:"nextauth-auth-js",auth:"signed-credential",fields:[field("secret","Auth.js secret",["AUTH_SECRET","NEXTAUTH_SECRET"])],verify:async v=>new Response(v.secret.length>=32?"{}":"secret too short",{status:v.secret.length>=32?200:400})},
 {id:"passport-js",auth:"signed-credential",fields:[field("sessionSecret","Session secret",["SESSION_SECRET"])],verify:async v=>new Response(v.sessionSecret.length>=32?"{}":"secret too short",{status:v.sessionSecret.length>=32?200:400})},
 {id:"stytch",auth:"username-password",fields:[field("projectId","Project ID",["STYTCH_PROJECT_ID"],false),field("secret","Secret",["STYTCH_SECRET"])],verify:v=>get("https://api.stytch.com/v1/projects",basic(v.projectId,v.secret))},
 {id:"descope",auth:"api-key",fields:[field("projectId","Project ID",["DESCOPE_PROJECT_ID"],false),field("managementKey","Management key",["DESCOPE_MANAGEMENT_KEY"])],verify:v=>get("https://api.descope.com/v1/mgmt/tenant/all",{authorization:`Bearer ${v.projectId}:${v.managementKey}`})},
 {id:"sqlite",auth:"connection-string",fields:[field("path","Database file",["SQLITE_PATH","DATABASE_URL"],false)],verify:async v=>{const sqlite=await import("sqlite3");const file=v.path.replace(/^file:/,"");return new Promise<Response>(resolve=>{const db=new sqlite.Database(file,error=>{if(error)return resolve(new Response("failed",{status:401}));db.get("SELECT 1 AS ok",queryError=>db.close(()=>resolve(new Response(queryError?"failed":"{}",{status:queryError?401:200}))));});});}},
 {id:"microsoft-sql-server",auth:"connection-string",fields:[field("url","SQL Server connection string",["SQLSERVER_URL","MSSQL_URL","DATABASE_URL"])],verify:async v=>{const sql=await import("mssql");const pool=await sql.connect(v.url);try{await pool.query("SELECT 1 AS ok");return new Response("{}",{status:200});}finally{await pool.close();}}},
 {id:"oracle",auth:"username-password",fields:[field("user","Database user",["ORACLE_USER"],false),field("password","Database password",["ORACLE_PASSWORD"]),field("connectString","Connect string",["ORACLE_CONNECT_STRING"],false)],verify:async v=>{const oracle=await import("oracledb");const connection=await oracle.getConnection({user:v.user,password:v.password,connectString:v.connectString});try{await connection.execute("SELECT 1 FROM DUAL");return new Response("{}",{status:200});}finally{await connection.close();}}},
 {id:"cockroachdb",auth:"connection-string",fields:[field("url","Database URL",["COCKROACH_DATABASE_URL","DATABASE_URL"])],verify:async v=>{const {Client}=await import("pg");const client=new Client({connectionString:v.url,connectionTimeoutMillis:8000});try{await client.connect();await client.query("SELECT 1");return new Response("{}",{status:200});}finally{await client.end().catch(()=>undefined);}}},
 {id:"neon",auth:"connection-string",fields:[field("url","Database URL",["NEON_DATABASE_URL","DATABASE_URL"])],verify:async v=>{const {Client}=await import("pg");const client=new Client({connectionString:v.url,connectionTimeoutMillis:8000});try{await client.connect();await client.query("SELECT 1");return new Response("{}",{status:200});}finally{await client.end().catch(()=>undefined);}}},
 {id:"planetscale",auth:"connection-string",fields:[field("url","Database URL",["PLANETSCALE_DATABASE_URL","DATABASE_URL"])],verify:async v=>{const {createConnection}=await import("mysql2/promise");const client=await createConnection({uri:v.url,connectTimeout:8000});try{await client.query("SELECT 1");return new Response("{}",{status:200});}finally{await client.end();}}},
 {id:"dynamodb",auth:"signed-credential",fields:[field("accessKeyId","Access key ID",["AWS_ACCESS_KEY_ID"],false),field("secretAccessKey","Secret access key",["AWS_SECRET_ACCESS_KEY"]),field("region","Region",["AWS_REGION"],false),field("sessionToken","Session token",["AWS_SESSION_TOKEN"],true,false)],verify:async v=>{const {DynamoDBClient,ListTablesCommand}=await import("@aws-sdk/client-dynamodb");const client=new DynamoDBClient({region:v.region,credentials:{accessKeyId:v.accessKeyId,secretAccessKey:v.secretAccessKey,...(v.sessionToken?{sessionToken:v.sessionToken}:{})}});try{await client.send(new ListTablesCommand({Limit:1}));return new Response("{}",{status:200});}finally{client.destroy();}}},
 {id:"firestore",auth:"service-account",fields:[field("projectId","Project ID",["GOOGLE_CLOUD_PROJECT"],false),field("serviceAccount","Service account JSON",["GOOGLE_APPLICATION_CREDENTIALS_JSON"])],verify:async v=>{const {Firestore}=await import("@google-cloud/firestore");const credentials=JSON.parse(v.serviceAccount);const client=new Firestore({projectId:v.projectId,credentials});await client.listCollections();return new Response("{}",{status:200});}},
 {id:"cosmos-db",auth:"api-key",fields:[field("endpoint","Cosmos endpoint",["COSMOS_ENDPOINT"],false),field("key","Account key",["COSMOS_KEY"])],verify:async v=>{const {CosmosClient}=await import("@azure/cosmos");const client=new CosmosClient({endpoint:v.endpoint,key:v.key});await client.databases.readAll().fetchNext();return new Response("{}",{status:200});}},
 {id:"upstash",auth:"api-key",fields:[field("url","REST URL",["UPSTASH_REDIS_REST_URL"],false),field("token","REST token",["UPSTASH_REDIS_REST_TOKEN"])],verify:v=>get(`${v.url.replace(/\/$/,"")}/ping`,bearer(v.token))},
 {id:"elasticsearch",auth:"api-key",fields:[field("url","Elasticsearch URL",["ELASTICSEARCH_URL"],false),field("apiKey","API key",["ELASTICSEARCH_API_KEY"])],verify:v=>get(`${v.url.replace(/\/$/,"")}/_security/_authenticate`,{authorization:`ApiKey ${v.apiKey}`})},
 {id:"opensearch",auth:"username-password",fields:[field("url","OpenSearch URL",["OPENSEARCH_URL"],false),field("username","Username",["OPENSEARCH_USERNAME"],false),field("password","Password",["OPENSEARCH_PASSWORD"])],verify:v=>get(`${v.url.replace(/\/$/,"")}/_cluster/health`,basic(v.username,v.password))},
 {id:"algolia",auth:"api-key",fields:[field("appId","Application ID",["ALGOLIA_APP_ID"],false),field("apiKey","Admin API key",["ALGOLIA_ADMIN_API_KEY"])],verify:v=>get(`https://${encodeURIComponent(v.appId)}-dsn.algolia.net/1/indexes?hitsPerPage=1`,{"x-algolia-application-id":v.appId,"x-algolia-api-key":v.apiKey})},
 {id:"meilisearch",auth:"api-key",fields:[field("url","Meilisearch URL",["MEILISEARCH_HOST"],false),field("apiKey","Master key",["MEILISEARCH_MASTER_KEY"])],verify:v=>get(`${v.url.replace(/\/$/,"")}/keys?limit=1`,bearer(v.apiKey))},
 {id:"pinecone",auth:"api-key",fields:[field("apiKey","API key",["PINECONE_API_KEY"])],verify:v=>get("https://api.pinecone.io/indexes",{"Api-Key":v.apiKey,"X-Pinecone-API-Version":"2025-04"})},
 {id:"weaviate",auth:"api-key",fields:[field("url","Cluster URL",["WEAVIATE_URL"],false),field("apiKey","API key",["WEAVIATE_API_KEY"])],verify:v=>get(`${v.url.replace(/\/$/,"")}/v1/meta`,bearer(v.apiKey))},
 {id:"qdrant",auth:"api-key",fields:[field("url","Cluster URL",["QDRANT_URL"],false),field("apiKey","API key",["QDRANT_API_KEY"])],verify:v=>get(`${v.url.replace(/\/$/,"")}/collections`,{"api-key":v.apiKey})},
 {id:"aws",auth:"signed-credential",fields:[field("accessKeyId","Access key ID",["AWS_ACCESS_KEY_ID"],false),field("secretAccessKey","Secret access key",["AWS_SECRET_ACCESS_KEY"]),field("region","Region",["AWS_REGION"],false),field("sessionToken","Session token",["AWS_SESSION_TOKEN"],true,false)],verify:async v=>{const {STSClient,GetCallerIdentityCommand}=await import("@aws-sdk/client-sts");const client=new STSClient({region:v.region,credentials:{accessKeyId:v.accessKeyId,secretAccessKey:v.secretAccessKey,...(v.sessionToken?{sessionToken:v.sessionToken}:{})}});try{await client.send(new GetCallerIdentityCommand({}));return new Response("{}",{status:200});}finally{client.destroy();}}},
 {id:"microsoft-azure",auth:"access-token",fields:[field("accessToken","Azure management access token",["AZURE_ACCESS_TOKEN"])],verify:v=>get("https://management.azure.com/subscriptions?api-version=2022-12-01",bearer(v.accessToken))},
 {id:"google-cloud",auth:"access-token",fields:[field("accessToken","Google Cloud access token",["GOOGLE_CLOUD_ACCESS_TOKEN"])],verify:v=>get("https://cloudresourcemanager.googleapis.com/v1/projects?pageSize=1",bearer(v.accessToken))},
 {id:"cloudflare",auth:"api-key",fields:[field("apiToken","API token",["CLOUDFLARE_API_TOKEN"])],verify:v=>get("https://api.cloudflare.com/client/v4/user/tokens/verify",bearer(v.apiToken))},
 {id:"vercel",auth:"access-token",fields:[field("token","Access token",["VERCEL_TOKEN"])],verify:v=>get("https://api.vercel.com/v2/user",bearer(v.token))},
 {id:"netlify",auth:"access-token",fields:[field("token","Personal access token",["NETLIFY_AUTH_TOKEN"])],verify:v=>get("https://api.netlify.com/api/v1/user",bearer(v.token))},
 {id:"render",auth:"api-key",fields:[field("apiKey","API key",["RENDER_API_KEY"])],verify:v=>get("https://api.render.com/v1/owners?limit=1",bearer(v.apiKey))},
 {id:"railway",auth:"api-key",fields:[field("apiToken","API token",["RAILWAY_API_TOKEN"])],verify:v=>request("https://backboard.railway.com/graphql/v2",{method:"POST",headers:{...bearer(v.apiToken),"content-type":"application/json"},body:JSON.stringify({query:"query { me { id email } }"})})},
 {id:"fly-io",auth:"access-token",fields:[field("apiToken","API token",["FLY_API_TOKEN"])],verify:v=>get("https://api.machines.dev/v1/apps",bearer(v.apiToken))},
 {id:"digitalocean",auth:"access-token",fields:[field("token","Personal access token",["DIGITALOCEAN_TOKEN"])],verify:v=>get("https://api.digitalocean.com/v2/account",bearer(v.token))},
 {id:"heroku",auth:"api-key",fields:[field("apiKey","API key",["HEROKU_API_KEY"])],verify:v=>get("https://api.heroku.com/account",{...bearer(v.apiKey),accept:"application/vnd.heroku+json; version=3"})},
 {id:"gitlab",auth:"access-token",fields:[field("token","Personal access token",["GITLAB_TOKEN"])],verify:v=>get("https://gitlab.com/api/v4/user",{"PRIVATE-TOKEN":v.token})},
 {id:"bitbucket",auth:"access-token",fields:[field("accessToken","Access token",["BITBUCKET_ACCESS_TOKEN"])],verify:v=>get("https://api.bitbucket.org/2.0/user",bearer(v.accessToken))},
 {id:"azure-devops",auth:"access-token",fields:[field("organization","Organization",["AZURE_DEVOPS_ORG"],false),field("token","Personal access token",["AZURE_DEVOPS_TOKEN"])],verify:v=>get(`https://dev.azure.com/${encodeURIComponent(v.organization)}/_apis/projects?$top=1&api-version=7.1`,basic("",v.token))},
 {id:"jira",auth:"api-key",fields:[field("siteUrl","Jira site URL",["JIRA_BASE_URL"],false),field("email","Account email",["JIRA_EMAIL"],false),field("apiToken","API token",["JIRA_API_TOKEN"])],verify:v=>get(`${v.siteUrl.replace(/\/$/,"")}/rest/api/3/myself`,basic(v.email,v.apiToken))},
 {id:"linear",auth:"api-key",fields:[field("apiKey","API key",["LINEAR_API_KEY"])],verify:v=>request("https://api.linear.app/graphql",{method:"POST",headers:{authorization:v.apiKey,"content-type":"application/json"},body:JSON.stringify({query:"query { viewer { id name } }"})})},
 {id:"sentry",auth:"access-token",fields:[field("authToken","Auth token",["SENTRY_AUTH_TOKEN"])],verify:v=>get("https://sentry.io/api/0/",bearer(v.authToken))},
 {id:"datadog",auth:"api-key",fields:[field("apiKey","API key",["DD_API_KEY"]),field("appKey","Application key",["DD_APP_KEY"])],verify:v=>get("https://api.datadoghq.com/api/v2/current_user",{"DD-API-KEY":v.apiKey,"DD-APPLICATION-KEY":v.appKey})},
 {id:"new-relic",auth:"api-key",fields:[field("userKey","User API key",["NEW_RELIC_USER_API_KEY"])],verify:v=>request("https://api.newrelic.com/graphql",{method:"POST",headers:{"API-Key":v.userKey,"content-type":"application/json"},body:JSON.stringify({query:"{ actor { user { id name } } }"})})},
 {id:"pagerduty",auth:"api-key",fields:[field("apiToken","API token",["PAGERDUTY_API_TOKEN"])],verify:v=>get("https://api.pagerduty.com/users?limit=1",{authorization:`Token token=${v.apiToken}`,accept:"application/vnd.pagerduty+json;version=2"})},
 {id:"paypal",auth:"oauth",fields:[field("clientId","Client ID",["PAYPAL_CLIENT_ID"],false),field("clientSecret","Client secret",["PAYPAL_CLIENT_SECRET"]),field("environment","Environment",["PAYPAL_ENVIRONMENT"],false,false)],verify:v=>request(v.environment==="live"?"https://api-m.paypal.com/v1/oauth2/token":"https://api-m.sandbox.paypal.com/v1/oauth2/token",{method:"POST",headers:{...basic(v.clientId,v.clientSecret),"content-type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"})},
 {id:"square",auth:"access-token",fields:[field("accessToken","Access token",["SQUARE_ACCESS_TOKEN"])],verify:v=>get("https://connect.squareup.com/v2/locations",{...bearer(v.accessToken),"Square-Version":"2026-01-22"})},
];

export const executableProviderIds=providerAdapterSpecs.map(spec=>spec.id);
const nativeLocalAgentPending=new Set(["amazon-ses","amazon-cognito","nextauth-auth-js","passport-js","sqlite","microsoft-sql-server","oracle","cockroachdb","neon","planetscale","dynamodb","firestore","cosmos-db","aws"]);
export function executableProviderDefinition(id:string){const spec=providerAdapterSpecs.find(item=>item.id===id);return spec?{auth:spec.auth,authenticationMethods:[spec.auth],preferredAuthenticationMethod:spec.auth,fields:spec.fields,deploymentMappings:Object.fromEntries(spec.fields.flatMap(item=>item.env.map(name=>[name,name]))),maturity:"adapter" as const,executionKind:"credential" as const,localAgentTest:!nativeLocalAgentPending.has(id),...(["vercel","netlify"].includes(id)?{hostingDeploymentWriter:true}:{})}:undefined;}
export async function verifyProviderAdapter(id:string,values:Record<string,string>):Promise<VerificationResult>{const spec=providerAdapterSpecs.find(item=>item.id===id);if(!spec)return{ok:false,status:"failed",message:"No executable provider adapter is registered."};try{const response=await spec.verify(values);const body=await response.text();if(response.ok)return{ok:true,status:"configured",message:"Authentication succeeded and the provider account endpoint is reachable."};const expired=response.status===401&&/expired/i.test(body);const revoked=response.status===401&&/(revoked|invalid|unauthorized)/i.test(body);return{ok:false,status:expired?"expired":revoked?"revoked":"failed",message:expired?"Credential expired. Reconnect the service.":revoked?"Credential was revoked or rejected. Reconnect the service.":`Provider authentication failed (HTTP ${response.status}). Check account access, credential scope, and environment.`};}catch{return{ok:false,status:"failed",message:"Provider connection failed. Check network access, credential scope, and environment."};}}
export async function providerRequestDescriptor(id:string,values:Record<string,string>){const spec=providerAdapterSpecs.find(item=>item.id===id);if(!spec)throw new Error("No executable provider adapter is registered.");let captured:{url:string;method:string;headers:Record<string,string>;body?:string}|undefined;const capture:typeof fetch=async(input,init)=>{const headers=Object.fromEntries(new Headers(init?.headers).entries());captured={url:String(input),method:init?.method||"GET",headers,...(init?.body?{body:init.body instanceof URLSearchParams?init.body.toString():String(init.body)}:{})};return new Response("{}",{status:200});};await requestContext.run(capture,()=>spec.verify(values));if(!captured)throw new Error("This adapter uses a native SDK and requires a Local Agent runtime package before local testing.");return captured;}
