import "server-only";
import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import type { CredentialScope, CredentialStatus, CredentialSummary } from "@/lib/integrations/types";

type Stored = { scope: CredentialScope; values: Record<string,string>; status: CredentialStatus; createdAt:string; updatedAt:string; lastVerifiedAt?:string; error?:string };
type Envelope = { version:1; iv:string; tag:string; ciphertext:string };
const root = path.join(process.cwd(), ".foundry-data", "credentials");
const fallbackKeyFile = path.join(root, ".local-master-key");
const scopeIndexFile = path.join(root, ".scope-index.json");
const scopeKey = (scope: CredentialScope) => createHash("sha256").update(JSON.stringify(scope)).digest("hex");
const fileFor = (scope: CredentialScope) => path.join(root, `${scopeKey(scope)}.enc`);
function cloudEndpoint(scope:CredentialScope){const base=process.env.FOUNDRY_CLOUD_SECRET_ENDPOINT;if(!base)throw new Error("Cloud secret storage is unavailable until FOUNDRY_CLOUD_SECRET_ENDPOINT is configured.");return`${base.replace(/\/$/,"")}/api/integrations/cloud-secrets/${scopeKey(scope)}`;}
async function cloudEnvelope(scope:CredentialScope,method:"GET"|"PUT"|"DELETE",envelope?:Envelope){const token=process.env.FOUNDRY_CLOUD_SECRET_TOKEN;if(!token)throw new Error("Cloud secret storage is unavailable until FOUNDRY_CLOUD_SECRET_TOKEN is configured.");const response=await fetch(cloudEndpoint(scope),{method,headers:{authorization:`Bearer ${token}`,...(envelope?{"content-type":"application/json"}:{})},body:envelope?JSON.stringify({scope:{userId:scope.userId,workspaceId:scope.workspaceId,projectId:scope.projectId,environment:scope.environment,provider:scope.provider},envelope}):undefined,cache:"no-store"});if(method==="GET"&&response.status===404)return undefined;if(!response.ok)throw new Error(`Encrypted cloud secret operation failed (HTTP ${response.status}).`);if(method!=="GET")return undefined;const payload=await response.json() as {envelope?:Envelope};if(!payload.envelope)throw new Error("Encrypted cloud secret response was malformed.");return payload.envelope;}
async function writeEnvelope(scope:CredentialScope,envelope:Envelope){if(scope.location==="cloud"){await cloudEnvelope(scope,"PUT",envelope);return;}await writeFile(fileFor(scope),JSON.stringify(envelope),{encoding:"utf8",mode:0o600});}

async function masterKey(location: "local" | "cloud") {
  const configured = location === "cloud" ? process.env.FOUNDRY_CLOUD_SECRET_KEY : process.env.FOUNDRY_LOCAL_SECRET_KEY;
  if (configured) return createHash("sha256").update(configured).digest();
  if (location === "cloud") throw new Error("Cloud secret storage is unavailable until FOUNDRY_CLOUD_SECRET_KEY is configured.");
  await mkdir(root, { recursive:true });
  try { return Buffer.from(await readFile(fallbackKeyFile, "utf8"), "base64"); }
  catch { const key = randomBytes(32); await writeFile(fallbackKeyFile, key.toString("base64"), { encoding:"utf8", mode:0o600 }); return key; }
}
function mask(value:string) { if (!value) return "Not set"; return value.length < 8 ? "••••" : `${value.slice(0,2)}••••${value.slice(-3)}`; }
function summary(record:Stored):CredentialSummary { return { provider:record.scope.provider, scope:record.scope, status:record.status, fields:Object.fromEntries(Object.entries(record.values).map(([k,v])=>[k,mask(v)])), createdAt:record.createdAt, updatedAt:record.updatedAt, lastVerifiedAt:record.lastVerifiedAt, error:record.error }; }
async function encrypt(record:Stored) { const key=await masterKey(record.scope.location); const iv=randomBytes(12); const cipher=createCipheriv("aes-256-gcm",key,iv); const ciphertext=Buffer.concat([cipher.update(JSON.stringify(record)),cipher.final()]); return { version:1 as const, iv:iv.toString("base64"),tag:cipher.getAuthTag().toString("base64"),ciphertext:ciphertext.toString("base64") }; }
async function decrypt(scope:CredentialScope,envelope:Envelope) { const decipher=createDecipheriv("aes-256-gcm",await masterKey(scope.location),Buffer.from(envelope.iv,"base64")); decipher.setAuthTag(Buffer.from(envelope.tag,"base64")); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(envelope.ciphertext,"base64")),decipher.final()]).toString("utf8")) as Stored; }
async function readScopeIndex():Promise<CredentialScope[]>{try{const value=JSON.parse(await readFile(scopeIndexFile,"utf8"));return Array.isArray(value)?value:[];}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return[];throw error;}}
async function writeScopeIndex(scopes:CredentialScope[]){await mkdir(root,{recursive:true});const temporary=`${scopeIndexFile}.${randomBytes(4).toString("hex")}.tmp`;await writeFile(temporary,JSON.stringify(scopes),{encoding:"utf8",mode:0o600});await rename(temporary,scopeIndexFile);}
async function indexScope(scope:CredentialScope){const scopes=await readScopeIndex();if(!scopes.some(item=>scopeKey(item)===scopeKey(scope)))await writeScopeIndex([...scopes,scope]);}

export async function getCredential(scope:CredentialScope) { try { const envelope=scope.location==="cloud"?await cloudEnvelope(scope,"GET"):JSON.parse(await readFile(fileFor(scope),"utf8")) as Envelope;return envelope?await decrypt(scope,envelope):undefined; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined; throw error; } }
export async function saveCredential(scope:CredentialScope,values:Record<string,string>,replace=false) { const prior=await getCredential(scope); if (prior && !replace) throw new Error("A credential already exists. Confirm replacement before rotating it."); const now=new Date().toISOString(); const record:Stored={scope,values,status:"unverified",createdAt:prior?.createdAt||now,updatedAt:now}; await mkdir(root,{recursive:true});if(scope.location==="cloud")await writeEnvelope(scope,await encrypt(record));else{const target=fileFor(scope);const temporary=`${target}.${randomBytes(4).toString("hex")}.tmp`;await writeFile(temporary,JSON.stringify(await encrypt(record)),{encoding:"utf8",mode:0o600});await rename(temporary,target);} await indexScope(scope); return summary(record); }
export async function updateCredentialStatus(scope:CredentialScope,status:CredentialStatus,error?:string) { const record=await getCredential(scope); if (!record) return undefined; record.status=status; record.error=error; record.updatedAt=new Date().toISOString(); if (status==="configured") record.lastVerifiedAt=record.updatedAt; await writeEnvelope(scope,await encrypt(record)); return summary(record); }
export async function removeCredential(scope:CredentialScope,confirmed=false) { if (!confirmed) throw new Error("Credential removal requires explicit confirmation."); const { unlink }=await import("node:fs/promises"); try { if(scope.location==="cloud")await cloudEnvelope(scope,"DELETE");else await unlink(fileFor(scope));await writeScopeIndex((await readScopeIndex()).filter(item=>scopeKey(item)!==scopeKey(scope))); return true; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return false; throw error; } }
export async function credentialSummary(scope:CredentialScope) { const record=await getCredential(scope); return record ? summary(record) : undefined; }
export async function verifiedCredentialsForProject(input:{userId:string;workspaceId?:string;projectId:string;environment:string;location:"local"|"cloud"}){let scopes=(await readScopeIndex()).filter(scope=>scope.userId===input.userId&&scope.projectId===input.projectId&&scope.environment===input.environment&&scope.location===input.location);if(input.workspaceId)scopes=scopes.filter(scope=>scope.workspaceId===input.workspaceId);else if(new Set(scopes.map(scope=>scope.workspaceId)).size>1)return[];const records:Stored[]=[];for(const scope of scopes){const record=await getCredential(scope);if(record?.status==="configured")records.push(record);}return records;}
