import { afterAll, afterEach, describe, expect, it, vi } from "vitest";
import { credentialSummary, getCredential, removeCredential, saveCredential, updateCredentialStatus, verifiedCredentialsForProject } from "@/lib/integrations/secret-store";
import { deploymentEnvironment, normalizeScope } from "@/lib/integrations/manager";
import type { CredentialScope } from "@/lib/integrations/types";
const run=`vitest-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const scope=(projectId:string,location:"local"|"cloud"="local"):CredentialScope=>({userId:run,workspaceId:"workspace",projectId,environment:"test",provider:"openai",location});
const made:CredentialScope[]=[];
afterAll(async()=>{for(const item of made)await removeCredential(item,true).catch(()=>undefined);});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();vi.unstubAllGlobals();});
describe("encrypted scoped storage",()=>{
 it("masks saved values and separates projects",async()=>{const a=scope("a"),b=scope("b");made.push(a,b);await saveCredential(a,{apiKey:"sk-project-a-secret"});expect((await credentialSummary(a))?.fields.apiKey).not.toContain("project-a-secret");expect(await getCredential(b)).toBeUndefined();});
 it("separates local and cloud key domains",async()=>{const local=scope("location"),cloud=scope("location","cloud");made.push(local);await saveCredential(local,{apiKey:"local-secret"});await expect(getCredential(cloud)).rejects.toThrow("FOUNDRY_CLOUD_SECRET_TOKEN");await expect(saveCredential(cloud,{apiKey:"cloud-secret"})).rejects.toThrow("FOUNDRY_CLOUD_SECRET_TOKEN");});
 it("persists only encrypted envelopes through the remote cloud backend",async()=>{const cloud=scope("remote-cloud","cloud");made.push(cloud);vi.stubEnv("FOUNDRY_CLOUD_SECRET_TOKEN","backend-token");vi.stubEnv("FOUNDRY_CLOUD_SECRET_KEY","encryption-key");vi.stubEnv("FOUNDRY_CLOUD_SECRET_ENDPOINT","https://secrets.foundry.test");let envelope:unknown;const request=vi.fn(async(_url:string,init?:RequestInit)=>{if(init?.method==="GET")return envelope?new Response(JSON.stringify({envelope}),{status:200,headers:{"content-type":"application/json"}}):new Response(null,{status:404});if(init?.method==="PUT"){const payload=JSON.parse(String(init.body));envelope=payload.envelope;expect(String(init.body)).not.toContain("remote-secret");return new Response(null,{status:204});}if(init?.method==="DELETE"){envelope=undefined;return new Response(null,{status:204});}return new Response(null,{status:400});});vi.stubGlobal("fetch",request);await saveCredential(cloud,{apiKey:"remote-secret"});expect((await getCredential(cloud))?.values.apiKey).toBe("remote-secret");await removeCredential(cloud,true);expect(request).toHaveBeenCalledWith(expect.stringContaining("/api/integrations/cloud-secrets/"),expect.objectContaining({method:"DELETE"}));});
 it("requires confirmation to rotate and remove",async()=>{const item=scope("rotation");made.push(item);await saveCredential(item,{apiKey:"first-secret"});await expect(saveCredential(item,{apiKey:"second-secret"})).rejects.toThrow("Confirm replacement");await saveCredential(item,{apiKey:"second-secret"},true);expect((await getCredential(item))?.values.apiKey).toBe("second-secret");await expect(removeCredential(item,false)).rejects.toThrow("explicit confirmation");});
 it("blocks wrong-environment lookup",async()=>{const item=scope("env");made.push(item);await saveCredential(item,{apiKey:"secret"});expect(await getCredential({...item,environment:"production"})).toBeUndefined();});
 it("fails closed when a runtime lookup does not identify an ambiguous workspace",async()=>{const first={...scope("shared-project"),workspaceId:"workspace-a"};const second={...scope("shared-project"),workspaceId:"workspace-b"};made.push(first,second);await saveCredential(first,{apiKey:"first-secret"});await saveCredential(second,{apiKey:"second-secret"});await updateCredentialStatus(first,"configured");await updateCredentialStatus(second,"configured");expect(await verifiedCredentialsForProject({userId:run,projectId:"shared-project",environment:"test",location:"local"})).toEqual([]);expect((await verifiedCredentialsForProject({userId:run,workspaceId:"workspace-a",projectId:"shared-project",environment:"test",location:"local"}))[0]?.values.apiKey).toBe("first-secret");});
 it("requires permission and verified status for deployment injection",async()=>{const item=scope("deploy");made.push(item);await saveCredential(item,{apiKey:"deploy-secret"});await expect(deploymentEnvironment(item,false)).rejects.toThrow("explicit permission");await expect(deploymentEnvironment(item,true)).rejects.toThrow("verified");await updateCredentialStatus(item,"configured");const deployment=await deploymentEnvironment(item,true);expect(deployment.names).toEqual(["OPENAI_API_KEY"]);const injected:Record<string,string>={};await deployment.inject(async(k,v)=>{injected[k]=v;});expect(injected.OPENAI_API_KEY).toBe("deploy-secret");});
 it("rejects incomplete and invalid scopes",()=>{expect(()=>normalizeScope({provider:"openai",userId:"",workspaceId:"w",projectId:"p",environment:"test"})).toThrow("User id");});
});
